# Japanese Vocabulary Database - Part 5 (Words 801-1000)

VOCAB_PART5 = [
    # Advanced Concepts (801-850)
    {"kanji": "相対", "kana": "そうたい", "romaji": "soutai", "english": "Relativity", "thai": "ความสัมพันธ์", "arabic": "نسبية", "russian": "Относительность"},
    {"kanji": "絶対", "kana": "ぜったい", "romaji": "zettai", "english": "Absolute", "thai": "สัมบูรณ์", "arabic": "مطلق", "russian": "Абсолютный"},
    {"kanji": "相互", "kana": "そうご", "romaji": "sougo", "english": "Mutual", "thai": "ซึ่งกันและกัน", "arabic": "متبادل", "russian": "Взаимный"},
    {"kanji": "一方的", "kana": "いっぽうてき", "romaji": "ippouteki", "english": "Unilateral", "thai": "ฝ่ายเดียว", "arabic": "أحادي", "russian": "Односторонний"},
    {"kanji": "双方", "kana": "そうほう", "romaji": "souhou", "english": "Both sides", "thai": "ทั้งสองฝ่าย", "arabic": "كلا الطرفين", "russian": "Обе стороны"},
    {"kanji": "全体", "kana": "ぜんたい", "romaji": "zentai", "english": "Whole", "thai": "ทั้งหมด", "arabic": "كلي", "russian": "Целое"},
    {"kanji": "部分", "kana": "ぶぶん", "romaji": "bubun", "english": "Part", "thai": "ส่วน", "arabic": "جزء", "russian": "Часть"},
    {"kanji": "総合", "kana": "そうごう", "romaji": "sougou", "english": "Synthesis", "thai": "การสังเคราะห์", "arabic": "تركيب", "russian": "Синтез"},
    {"kanji": "個別", "kana": "こべつ", "romaji": "kobetsu", "english": "Individual", "thai": "แต่ละอัน", "arabic": "فردي", "russian": "Индивидуальный"},
    {"kanji": "一般", "kana": "いっぱん", "romaji": "ippan", "english": "General", "thai": "ทั่วไป", "arabic": "عام", "russian": "Общий"},
    {"kanji": "特殊", "kana": "とくしゅ", "romaji": "tokushu", "english": "Special", "thai": "พิเศษ", "arabic": "خاص", "russian": "Особый"},
    {"kanji": "通常", "kana": "つうじょう", "romaji": "tsuujou", "english": "Normal", "thai": "ปกติ", "arabic": "عادي", "russian": "Обычный"},
    {"kanji": "異常", "kana": "いじょう", "romaji": "ijou", "english": "Abnormal", "thai": "ผิดปกติ", "arabic": "شاذ", "russian": "Аномальный"},
    {"kanji": "正常", "kana": "せいじょう", "romaji": "seijou", "english": "Normal", "thai": "ปกติ", "arabic": "طبيعي", "russian": "Нормальный"},
    {"kanji": "異例", "kana": "いれい", "romaji": "irei", "english": "Exceptional", "thai": "พิเศษ", "arabic": "استثنائي", "russian": "Исключительный"},
    {"kanji": "通例", "kana": "つうれい", "romaji": "tsuurei", "english": "Usual", "thai": "ตามปกติ", "arabic": "معتاد", "russian": "Обычный"},
    {"kanji": "例外", "kana": "れいがい", "romaji": "reigai", "english": "Exception", "thai": "ข้อยกเว้น", "arabic": "استثناء", "russian": "Исключение"},
    {"kanji": "原則", "kana": "げんそく", "romaji": "gensoku", "english": "Principle", "thai": "หลักการ", "arabic": "مبدأ", "russian": "Принцип"},
    {"kanji": "規則", "kana": "きそく", "romaji": "kisoku", "english": "Rule", "thai": "กฎ", "arabic": "قاعدة", "russian": "Правило"},
    {"kanji": "違例", "kana": "いれい", "romaji": "irei", "english": "Irregularity", "thai": "ความผิดปกติ", "arabic": "مخالفة", "russian": "Нарушение"},
    {"kanji": "合法", "kana": "ごうほう", "romaji": "gouhou", "english": "Legal", "thai": "ถูกกฎหมาย", "arabic": "قانوني", "russian": "Законный"},
    {"kanji": "違法", "kana": "いほう", "romaji": "ihou", "english": "Illegal", "thai": "ผิดกฎหมาย", "arabic": "غير قانوني", "russian": "Незаконный"},
    {"kanji": "合理", "kana": "ごうり", "romaji": "gouri", "english": "Rational", "thai": "มีเหตุผล", "arabic": "عقلاني", "russian": "Рациональный"},
    {"kanji": "不合理", "kana": "ふごうり", "romaji": "fugouri", "english": "Irrational", "thai": "ไร้เหตุผล", "arabic": "غير عقلاني", "russian": "Иррациональный"},
    {"kanji": "論理的", "kana": "ろんりてき", "romaji": "ronriteki", "english": "Logical", "thai": "เชิงตรรกะ", "arabic": "منطقي", "russian": "Логичный"},
    {"kanji": "非論理的", "kana": "ひろんりてき", "romaji": "hironriteki", "english": "Illogical", "thai": "ไม่มีตรรกะ", "arabic": "غير منطقي", "russian": "Нелогичный"},
    {"kanji": "科学的", "kana": "かがくてき", "romaji": "kagakuteki", "english": "Scientific", "thai": "ทางวิทยาศาสตร์", "arabic": "علمي", "russian": "Научный"},
    {"kanji": "非科学的", "kana": "ひかがくてき", "romaji": "hikagakuteki", "english": "Unscientific", "thai": "ไม่เป็นวิทยาศาสตร์", "arabic": "غير علمي", "russian": "Ненаучный"},
    {"kanji": "実証", "kana": "じっしょう", "romaji": "jisshou", "english": "Demonstration", "thai": "การพิสูจน์", "arabic": "إثبات", "russian": "Доказательство"},
    {"kanji": "推測", "kana": "すいそく", "romaji": "suisoku", "english": "Speculation", "thai": "การคาดการณ์", "arabic": "تخمين", "russian": "Предположение"},
    {"kanji": "実践", "kana": "じっせん", "romaji": "jissen", "english": "Practice", "thai": "การปฏิบัติ", "arabic": "ممارسة", "russian": "Практика"},
    {"kanji": "空論", "kana": "くうろん", "romaji": "kuuron", "english": "Empty theory", "thai": "ทฤษฎีที่ไม่ได้ผล", "arabic": "نظرية فارغة", "russian": "Пустая теория"},
    {"kanji": "実用", "kana": "じつよう", "romaji": "jitsuyou", "english": "Practical use", "thai": "การใช้งานจริง", "arabic": "استخدام عملي", "russian": "Практическое применение"},
    {"kanji": "机上", "kana": "きじょう", "romaji": "kijou", "english": "Theoretical", "thai": "เชิงทฤษฎี", "arabic": "نظري", "russian": "Теоретический"},
    {"kanji": "現実", "kana": "げんじつ", "romaji": "genjitsu", "english": "Reality", "thai": "ความเป็นจริง", "arabic": "واقع", "russian": "Реальность"},
    {"kanji": "理想", "kana": "りそう", "romaji": "risou", "english": "Ideal", "thai": "อุดมคติ", "arabic": "مثالي", "russian": "Идеал"},
    {"kanji": "現状", "kana": "げんじょう", "romaji": "genjou", "english": "Current state", "thai": "สถานะปัจจุบัน", "arabic": "الوضع الحالي", "russian": "Текущее состояние"},
    {"kanji": "願望", "kana": "がんぼう", "romaji": "ganbou", "english": "Desire", "thai": "ความปรารถนา", "arabic": "رغبة", "russian": "Желание"},
    {"kanji": "実態", "kana": "じったい", "romaji": "jittai", "english": "Actual situation", "thai": "สภาพจริง", "arabic": "الواقع الفعلي", "russian": "Действительное положение"},
    {"kanji": "建前", "kana": "たてまえ", "romaji": "tatemae", "english": "Facade", "thai": "หน้าบัง", "arabic": "واجهة", "russian": "Показная сторона"},
    {"kanji": "本音", "kana": "ほんね", "romaji": "honne", "english": "True feelings", "thai": "ความรู้สึกที่แท้จริง", "arabic": "مشاعر حقيقية", "russian": "Истинные чувства"},
    {"kanji": "表向き", "kana": "おもてむき", "romaji": "omotemuki", "english": "Outward", "thai": "ภายนอก", "arabic": "ظاهري", "russian": "Внешне"},
    {"kanji": "内実", "kana": "ないじつ", "romaji": "naijitsu", "english": "Substance", "thai": "แก่นแท้", "arabic": "جوهر", "russian": "Суть"},
    {"kanji": "形式", "kana": "けいしき", "romaji": "keishiki", "english": "Form", "thai": "รูปแบบ", "arabic": "شكل", "russian": "Форма"},
    {"kanji": "内容", "kana": "ないよう", "romaji": "naiyou", "english": "Content", "thai": "เนื้อหา", "arabic": "محتوى", "russian": "Содержание"},
    {"kanji": "外見", "kana": "がいけん", "romaji": "gaiken", "english": "Appearance", "thai": "รูปลักษณ์ภายนอก", "arabic": "مظهر", "russian": "Внешний вид"},
    {"kanji": "実質", "kana": "じっしつ", "romaji": "jisshitsu", "english": "Substance", "thai": "สาระสำคัญ", "arabic": "جوهر", "russian": "Сущность"},
    {"kanji": "名目", "kana": "めいもく", "romaji": "meimoku", "english": "Nominal", "thai": "เป็นชื่อ", "arabic": "اسمي", "russian": "Номинальный"},
    {"kanji": "実質的", "kana": "じっしつてき", "romaji": "jisshitsuteki", "english": "Substantial", "thai": "เป็นจริง", "arabic": "جوهري", "russian": "Существенный"},
    {"kanji": "名義", "kana": "めいぎ", "romaji": "meigi", "english": "Name", "thai": "นามสกุล", "arabic": "اسم", "russian": "Имя"},

    # Natural Phenomena (851-900)
    {"kanji": "現象", "kana": "げんしょう", "romaji": "genshou", "english": "Phenomenon", "thai": "ปรากฏการณ์", "arabic": "ظاهرة", "russian": "Явление"},
    {"kanji": "法則", "kana": "ほうそく", "romaji": "housoku", "english": "Law", "thai": "กฎ", "arabic": "قانون", "russian": "Закон"},
    {"kanji": "規律", "kana": "きりつ", "romaji": "kiritsu", "english": "Discipline", "thai": "ระเบียบวินัย", "arabic": "انضباط", "russian": "Дисциплина"},
    {"kanji": "偶然", "kana": "ぐうぜん", "romaji": "guuzen", "english": "Coincidence", "thai": "บังเอิญ", "arabic": "صدفة", "russian": "Случайность"},
    {"kanji": "必然", "kana": "ひつぜん", "romaji": "hitsuzen", "english": "Necessity", "thai": "ความจำเป็น", "arabic": "ضرورة", "russian": "Необходимость"},
    {"kanji": "運命", "kana": "うんめい", "romaji": "unmei", "english": "Fate", "thai": "ชะตากรรม", "arabic": "قدر", "russian": "Судьба"},
    {"kanji": "宿命", "kana": "しゅくめい", "romaji": "shukumei", "english": "Destiny", "thai": "โชคชะตา", "arabic": "مصير", "russian": "Предопределение"},
    {"kanji": "因果", "kana": "いんが", "romaji": "inga", "english": "Causality", "thai": "เหตุและผล", "arabic": "سببية", "russian": "Причинность"},
    {"kanji": "循環", "kana": "じゅんかん", "romaji": "junkan", "english": "Circulation", "thai": "การหมุนเวียน", "arabic": "دورة", "russian": "Циркуляция"},
    {"kanji": "連鎖", "kana": "れんさ", "romaji": "rensa", "english": "Chain", "thai": "ลูกโซ่", "arabic": "سلسلة", "russian": "Цепь"},
    {"kanji": "断絶", "kana": "だんぜつ", "romaji": "danzetsu", "english": "Severance", "thai": "การตัดขาด", "arabic": "انقطاع", "russian": "Разрыв"},
    {"kanji": "継続", "kana": "けいぞく", "romaji": "keizoku", "english": "Continuation", "thai": "การต่อเนื่อง", "arabic": "استمرار", "russian": "Продолжение"},
    {"kanji": "中絶", "kana": "ちゅうぜつ", "romaji": "chuuzetsu", "english": "Discontinuation", "thai": "การหยุดชะงัก", "arabic": "إجهاض", "russian": "Прерывание"},
    {"kanji": "恒久", "kana": "こうきゅう", "romaji": "koukyuu", "english": "Permanence", "thai": "ความถาวร", "arabic": "دائم", "russian": "Постоянство"},
    {"kanji": "暫定", "kana": "ざんてい", "romaji": "zantei", "english": "Provisional", "thai": "ชั่วคราว", "arabic": "مؤقت", "russian": "Временный"},
    {"kanji": "永続", "kana": "えいぞく", "romaji": "eizoku", "english": "Perpetuity", "thai": "ความยั่งยืน", "arabic": "دوام", "russian": "Вечность"},
    {"kanji": "刹那", "kana": "せつな", "romaji": "setsuna", "english": "Instant", "thai": "ชั่วขณะ", "arabic": "لحظة", "russian": "Мгновение"},
    {"kanji": "悠久", "kana": "ゆうきゅう", "romaji": "yuukyuu", "english": "Eternity", "thai": "นิรันดร", "arabic": "أزلية", "russian": "Вечность"},
    {"kanji": "束の間", "kana": "つかのま", "romaji": "tsukanoma", "english": "Brief", "thai": "ชั่วครู่", "arabic": "عابر", "russian": "Мимолётный"},
    {"kanji": "恒常性", "kana": "こうじょうせい", "romaji": "koujousei", "english": "Homeostasis", "thai": "ภาวะสมดุล", "arabic": "توازن", "russian": "Гомеостаз"},
    {"kanji": "可塑性", "kana": "かそせい", "romaji": "kasosei", "english": "Plasticity", "thai": "ความอ่อนตัว", "arabic": "مرونة", "russian": "Пластичность"},
    {"kanji": "弾力性", "kana": "だんりょくせい", "romaji": "danryokusei", "english": "Elasticity", "thai": "ความยืดหยุ่น", "arabic": "مرونة", "russian": "Эластичность"},
    {"kanji": "脆性", "kana": "ぜいせい", "romaji": "zeisei", "english": "Brittleness", "thai": "ความเปราะ", "arabic": "هشاشة", "russian": "Хрупкость"},
    {"kanji": "粘性", "kana": "ねんせい", "romaji": "nensei", "english": "Viscosity", "thai": "ความหนืด", "arabic": "لزوجة", "russian": "Вязкость"},
    {"kanji": "透明性", "kana": "とうめいせい", "romaji": "toumeisei", "english": "Transparency", "thai": "ความโปร่งใส", "arabic": "شفافية", "russian": "Прозрачность"},
    {"kanji": "不透明", "kana": "ふとうめい", "romaji": "futoumei", "english": "Opacity", "thai": "ความทึบแสง", "arabic": "عتامة", "russian": "Непрозрачность"},
    {"kanji": "透過", "kana": "とうか", "romaji": "touka", "english": "Transmission", "thai": "การทะลุผ่าน", "arabic": "نفاذية", "russian": "Проникновение"},
    {"kanji": "遮断", "kana": "しゃだん", "romaji": "shadan", "english": "Blocking", "thai": "การปิดกั้น", "arabic": "حجب", "russian": "Блокировка"},
    {"kanji": "浸透", "kana": "しんとう", "romaji": "shintou", "english": "Permeation", "thai": "การซึมผ่าน", "arabic": "تسرب", "russian": "Проникновение"},
    {"kanji": "拡散", "kana": "かくさん", "romaji": "kakusan", "english": "Diffusion", "thai": "การแพร่กระจาย", "arabic": "انتشار", "russian": "Диффузия"},
    {"kanji": "収斂", "kana": "しゅうれん", "romaji": "shuuren", "english": "Convergence", "thai": "การรวมกัน", "arabic": "تقارب", "russian": "Сходимость"},
    {"kanji": "分岐", "kana": "ぶんき", "romaji": "bunki", "english": "Bifurcation", "thai": "การแตกแขนง", "arabic": "تشعب", "russian": "Разветвление"},
    {"kanji": "合流", "kana": "ごうりゅう", "romaji": "gouryuu", "english": "Confluence", "thai": "การบรรจบ", "arabic": "التقاء", "russian": "Слияние"},
    {"kanji": "発散", "kana": "はっさん", "romaji": "hassan", "english": "Radiation", "thai": "การแผ่ออก", "arabic": "إشعاع", "russian": "Излучение"},
    {"kanji": "吸収", "kana": "きゅうしゅう", "romaji": "kyuushuu", "english": "Absorption", "thai": "การดูดซับ", "arabic": "امتصاص", "russian": "Поглощение"},
    {"kanji": "放出", "kana": "ほうしゅつ", "romaji": "houshutsu", "english": "Emission", "thai": "การปล่อยออก", "arabic": "انبعاث", "russian": "Выделение"},
    {"kanji": "蓄積", "kana": "ちくせき", "romaji": "chikuseki", "english": "Accumulation", "thai": "การสะสม", "arabic": "تراكم", "russian": "Накопление"},
    {"kanji": "消耗", "kana": "しょうもう", "romaji": "shoumou", "english": "Consumption", "thai": "การสิ้นเปลือง", "arabic": "استهلاك", "russian": "Расход"},
    {"kanji": "増殖", "kana": "ぞうしょく", "romaji": "zoushoku", "english": "Proliferation", "thai": "การขยายพันธุ์", "arabic": "تكاثر", "russian": "Размножение"},
    {"kanji": "減衰", "kana": "げんすい", "romaji": "gensui", "english": "Attenuation", "thai": "การลดลง", "arabic": "تلاشي", "russian": "Затухание"},
    {"kanji": "増幅", "kana": "ぞうふく", "romaji": "zoufuku", "english": "Amplification", "thai": "การขยาย", "arabic": "تضخيم", "russian": "Усиление"},
    {"kanji": "抑圧", "kana": "よくあつ", "romaji": "yokuatsu", "english": "Suppression", "thai": "การกด", "arabic": "قمع", "russian": "Подавление"},
    {"kanji": "促進", "kana": "そくしん", "romaji": "sokushin", "english": "Facilitation", "thai": "การส่งเสริม", "arabic": "تسهيل", "russian": "Ускорение"},
    {"kanji": "阻止", "kana": "そし", "romaji": "soshi", "english": "Prevention", "thai": "การป้องกัน", "arabic": "منع", "russian": "Предотвращение"},
    {"kanji": "誘導", "kana": "ゆうどう", "romaji": "yuudou", "english": "Induction", "thai": "การชักนำ", "arabic": "حث", "russian": "Индукция"},
    {"kanji": "抑止", "kana": "よくし", "romaji": "yokushi", "english": "Deterrence", "thai": "การยับยั้ง", "arabic": "ردع", "russian": "Сдерживание"},
    {"kanji": "誘引", "kana": "ゆういん", "romaji": "yuuin", "english": "Attraction", "thai": "การดึงดูด", "arabic": "جذب", "russian": "Притяжение"},
    {"kanji": "排斥", "kana": "はいせき", "romaji": "haiseki", "english": "Repulsion", "thai": "การผลัก", "arabic": "طرد", "russian": "Отталкивание"},
    {"kanji": "吸引", "kana": "きゅういん", "romaji": "kyuuin", "english": "Suction", "thai": "การดูด", "arabic": "شفط", "russian": "Всасывание"},

    # Final Advanced Terms (901-1000)
    {"kanji": "排出", "kana": "はいしゅつ", "romaji": "haishutsu", "english": "Discharge", "thai": "การปล่อยออก", "arabic": "تصريف", "russian": "Выброс"},
    {"kanji": "摂取", "kana": "せっしゅ", "romaji": "sesshu", "english": "Intake", "thai": "การรับเข้า", "arabic": "تناول", "russian": "Приём"},
    {"kanji": "排泄", "kana": "はいせつ", "romaji": "haisetsu", "english": "Excretion", "thai": "การขับถ่าย", "arabic": "إخراج", "russian": "Выделение"},
    {"kanji": "代謝", "kana": "たいしゃ", "romaji": "taisha", "english": "Metabolism", "thai": "การเผาผลาญ", "arabic": "استقلاب", "russian": "Метаболизм"},
    {"kanji": "同化", "kana": "どうか", "romaji": "douka", "english": "Assimilation", "thai": "การดูดซึม", "arabic": "استيعاب", "russian": "Ассимиляция"},
    {"kanji": "異化", "kana": "いか", "romaji": "ika", "english": "Dissimilation", "thai": "การสลาย", "arabic": "تفكك", "russian": "Диссимиляция"},
    {"kanji": "合成", "kana": "ごうせい", "romaji": "gousei", "english": "Synthesis", "thai": "การสังเคราะห์", "arabic": "تركيب", "russian": "Синтез"},
    {"kanji": "分解", "kana": "ぶんかい", "romaji": "bunkai", "english": "Decomposition", "thai": "การย่อยสลาย", "arabic": "تحلل", "russian": "Разложение"},
    {"kanji": "生成", "kana": "せいせい", "romaji": "seisei", "english": "Formation", "thai": "การเกิด", "arabic": "تكوين", "russian": "Образование"},
    {"kanji": "崩壊", "kana": "ほうかい", "romaji": "houkai", "english": "Disintegration", "thai": "การสลายตัว", "arabic": "تفكك", "russian": "Распад"},
    {"kanji": "結合", "kana": "けつごう", "romaji": "ketsugou", "english": "Combination", "thai": "การรวม", "arabic": "ارتباط", "russian": "Соединение"},
    {"kanji": "解離", "kana": "かいり", "romaji": "kairi", "english": "Dissociation", "thai": "การแตกตัว", "arabic": "انفصال", "russian": "Диссоциация"},
    {"kanji": "凝集", "kana": "ぎょうしゅう", "romaji": "gyoushuu", "english": "Coagulation", "thai": "การจับตัว", "arabic": "تجلط", "russian": "Коагуляция"},
    {"kanji": "拡張", "kana": "かくちょう", "romaji": "kakuchou", "english": "Expansion", "thai": "การขยาย", "arabic": "توسع", "russian": "Расширение"},
    {"kanji": "収縮", "kana": "しゅうしゅく", "romaji": "shuushuku", "english": "Contraction", "thai": "การหด", "arabic": "انكماش", "russian": "Сжатие"},
    {"kanji": "膨張", "kana": "ぼうちょう", "romaji": "bouchou", "english": "Swelling", "thai": "การพองขยาย", "arabic": "تمدد", "russian": "Вздутие"},
    {"kanji": "圧縮", "kana": "あっしゅく", "romaji": "asshuku", "english": "Compression", "thai": "การอัด", "arabic": "ضغط", "russian": "Сжатие"},
    {"kanji": "延伸", "kana": "えんしん", "romaji": "enshin", "english": "Extension", "thai": "การยืด", "arabic": "تمديد", "russian": "Вытягивание"},
    {"kanji": "屈曲", "kana": "くっきょく", "romaji": "kukkyoku", "english": "Bending", "thai": "การงอ", "arabic": "انحناء", "russian": "Изгиб"},
    {"kanji": "伸張", "kana": "しんちょう", "romaji": "shinchou", "english": "Stretching", "thai": "การยืด", "arabic": "تمدد", "russian": "Растяжение"},
    {"kanji": "捻転", "kana": "ねんてん", "romaji": "nenten", "english": "Torsion", "thai": "การบิด", "arabic": "التواء", "russian": "Кручение"},
    {"kanji": "歪曲", "kana": "わいきょく", "romaji": "waikyoku", "english": "Distortion", "thai": "การบิดเบือน", "arabic": "تشويه", "russian": "Искажение"},
    {"kanji": "整形", "kana": "せいけい", "romaji": "seikei", "english": "Shaping", "thai": "การปั้น", "arabic": "تشكيل", "russian": "Формовка"},
    {"kanji": "変形", "kana": "へんけい", "romaji": "henkei", "english": "Deformation", "thai": "การเสียรูป", "arabic": "تشوه", "russian": "Деформация"},
    {"kanji": "加工", "kana": "かこう", "romaji": "kakou", "english": "Processing", "thai": "การแปรรูป", "arabic": "تصنيع", "russian": "Обработка"},
    {"kanji": "劣化", "kana": "れっか", "romaji": "rekka", "english": "Degradation", "thai": "การเสื่อมสภาพ", "arabic": "تدهور", "russian": "Деградация"},
    {"kanji": "精製", "kana": "せいせい", "romaji": "seisei", "english": "Refining", "thai": "การกลั่น", "arabic": "تكرير", "russian": "Очистка"},
    {"kanji": "汚染", "kana": "おせん", "romaji": "osen", "english": "Contamination", "thai": "การปนเปื้อน", "arabic": "تلوث", "russian": "Загрязнение"},
    {"kanji": "浄化", "kana": "じょうか", "romaji": "jouka", "english": "Purification", "thai": "การทำให้บริสุทธิ์", "arabic": "تنقية", "russian": "Очищение"},
    {"kanji": "腐敗", "kana": "ふはい", "romaji": "fuhai", "english": "Corruption", "thai": "การเน่าเปื่อย", "arabic": "فساد", "russian": "Гниение"},
    {"kanji": "保存", "kana": "ほぞん", "romaji": "hozon", "english": "Preservation", "thai": "การเก็บรักษา", "arabic": "حفظ", "russian": "Сохранение"},
    {"kanji": "腐朽", "kana": "ふきゅう", "romaji": "fukyuu", "english": "Decay", "thai": "การเน่าผุ", "arabic": "تعفن", "russian": "Разложение"},
    {"kanji": "防腐", "kana": "ぼうふ", "romaji": "boufu", "english": "Antiseptic", "thai": "การป้องกันการเน่า", "arabic": "مضاد للتعفن", "russian": "Антисептический"},
    {"kanji": "酸化", "kana": "さんか", "romaji": "sanka", "english": "Oxidation", "thai": "การเกิดออกซิเดชัน", "arabic": "أكسدة", "russian": "Окисление"},
    {"kanji": "還元", "kana": "かんげん", "romaji": "kangen", "english": "Reduction", "thai": "การคืนสภาพ", "arabic": "اختزال", "russian": "Восстановление"},
    {"kanji": "中和", "kana": "ちゅうわ", "romaji": "chuuwa", "english": "Neutralization", "thai": "การทำให้เป็นกลาง", "arabic": "معادلة", "russian": "Нейтрализация"},
    {"kanji": "飽和", "kana": "ほうわ", "romaji": "houwa", "english": "Saturation", "thai": "ความอิ่มตัว", "arabic": "تشبع", "russian": "Насыщение"},
    {"kanji": "希釈", "kana": "きしゃく", "romaji": "kishaku", "english": "Dilution", "thai": "การเจือจาง", "arabic": "تخفيف", "russian": "Разбавление"},
    {"kanji": "濃縮", "kana": "のうしゅく", "romaji": "noushuku", "english": "Concentration", "thai": "การเข้มข้น", "arabic": "تركيز", "russian": "Концентрация"},
    {"kanji": "析出", "kana": "せきしゅつ", "romaji": "sekishutsu", "english": "Precipitation", "thai": "การตกผลึก", "arabic": "ترسب", "russian": "Осаждение"},
    {"kanji": "沈殿", "kana": "ちんでん", "romaji": "chinden", "english": "Sedimentation", "thai": "การตกตะกอน", "arabic": "ترسيب", "russian": "Осаждение"},
    {"kanji": "蒸留", "kana": "じょうりゅう", "romaji": "jouryuu", "english": "Distillation", "thai": "การกลั่น", "arabic": "تقطير", "russian": "Дистилляция"},
    {"kanji": "昇華", "kana": "しょうか", "romaji": "shouka", "english": "Sublimation", "thai": "การระเหิด", "arabic": "تسامي", "russian": "Сублимация"},
    {"kanji": "結晶", "kana": "けっしょう", "romaji": "kesshou", "english": "Crystallization", "thai": "การตกผลึก", "arabic": "تبلور", "russian": "Кристаллизация"},
    {"kanji": "融解", "kana": "ゆうかい", "romaji": "yuukai", "english": "Melting", "thai": "การละลาย", "arabic": "انصهار", "russian": "Плавление"},
    {"kanji": "凝固", "kana": "ぎょうこ", "romaji": "gyouko", "english": "Freezing", "thai": "การแข็งตัว", "arabic": "تجمد", "russian": "Замерзание"},
    {"kanji": "沸騰", "kana": "ふっとう", "romaji": "futtou", "english": "Boiling", "thai": "การเดือด", "arabic": "غليان", "russian": "Кипение"},
    {"kanji": "凝縮", "kana": "ぎょうしゅく", "romaji": "gyoushuku", "english": "Condensation", "thai": "การควบแน่น", "arabic": "تكثيف", "russian": "Конденсация"},
    {"kanji": "気化", "kana": "きか", "romaji": "kika", "english": "Vaporization", "thai": "การกลายเป็นไอ", "arabic": "تبخر", "russian": "Испарение"},
    {"kanji": "液化", "kana": "えきか", "romaji": "ekika", "english": "Liquefaction", "thai": "การเหลว", "arabic": "تسييل", "russian": "Сжижение"},
    {"kanji": "固化", "kana": "こか", "romaji": "koka", "english": "Solidification", "thai": "การแข็งตัว", "arabic": "تصلب", "russian": "Затвердевание"},
    {"kanji": "平衡", "kana": "へいこう", "romaji": "heikou", "english": "Equilibrium", "thai": "สมดุล", "arabic": "توازن", "russian": "Равновесие"},
    {"kanji": "不均衡", "kana": "ふきんこう", "romaji": "fukinkou", "english": "Imbalance", "thai": "ความไม่สมดุล", "arabic": "عدم توازن", "russian": "Дисбаланс"},
    {"kanji": "恒常", "kana": "こうじょう", "romaji": "koujou", "english": "Homeostasis", "thai": "ภาวะคงที่", "arabic": "ثبات", "russian": "Постоянство"},
    {"kanji": "変異", "kana": "へんい", "romaji": "hen'i", "english": "Variation", "thai": "การแปรผัน", "arabic": "تباين", "russian": "Вариация"},
    {"kanji": "遺伝", "kana": "いでん", "romaji": "iden", "english": "Heredity", "thai": "พันธุกรรม", "arabic": "وراثة", "russian": "Наследственность"},
    {"kanji": "変異", "kana": "へんい", "romaji": "hen'i", "english": "Mutation", "thai": "การกลายพันธุ์", "arabic": "طفرة", "russian": "Мутация"},
    {"kanji": "適応", "kana": "てきおう", "romaji": "tekiou", "english": "Adaptation", "thai": "การปรับตัว", "arabic": "تكيف", "russian": "Адаптация"},
    {"kanji": "淘汰", "kana": "とうた", "romaji": "touta", "english": "Selection", "thai": "การคัดเลือก", "arabic": "انتقاء", "russian": "Отбор"},
    {"kanji": "進化", "kana": "しんか", "romaji": "shinka", "english": "Evolution", "thai": "วิวัฒนาการ", "arabic": "تطور", "russian": "Эволюция"},
    {"kanji": "退化", "kana": "たいか", "romaji": "taika", "english": "Degeneration", "thai": "การเสื่อมถอย", "arabic": "تدهور", "russian": "Дегенерация"},
    {"kanji": "分化", "kana": "ぶんか", "romaji": "bunka", "english": "Differentiation", "thai": "การแยกตัว", "arabic": "تمايز", "russian": "Дифференциация"},
    {"kanji": "特化", "kana": "とっか", "romaji": "tokka", "english": "Specialization", "thai": "การเชี่ยวชาญ", "arabic": "تخصص", "russian": "Специализация"},
    {"kanji": "多様化", "kana": "たようか", "romaji": "tayouka", "english": "Diversification", "thai": "ความหลากหลาย", "arabic": "تنوع", "russian": "Диверсификация"},
    {"kanji": "単一化", "kana": "たんいつか", "romaji": "tan'itsuka", "english": "Unification", "thai": "การเป็นหนึ่งเดียว", "arabic": "توحيد", "russian": "Унификация"},
    {"kanji": "複合化", "kana": "ふくごうか", "romaji": "fukugouka", "english": "Complexification", "thai": "การซับซ้อน", "arabic": "تعقيد", "russian": "Усложнение"},
    {"kanji": "簡略化", "kana": "かんりゃくか", "romaji": "kanryakuka", "english": "Simplification", "thai": "การทำให้ง่าย", "arabic": "تبسيط", "russian": "Упрощение"},
    {"kanji": "体系化", "kana": "たいけいか", "romaji": "taikeika", "english": "Systematization", "thai": "การจัดระบบ", "arabic": "تنظيم", "russian": "Систематизация"},
    {"kanji": "規格化", "kana": "きかくか", "romaji": "kikakuka", "english": "Standardization", "thai": "การมาตรฐาน", "arabic": "توحيد المعايير", "russian": "Стандартизация"},
    {"kanji": "最適化", "kana": "さいてきか", "romaji": "saitekika", "english": "Optimization", "thai": "การเพิ่มประสิทธิภาพ", "arabic": "تحسين", "russian": "Оптимизация"},
    {"kanji": "効率化", "kana": "こうりつか", "romaji": "kouritsuka", "english": "Efficiency", "thai": "การทำให้มีประสิทธิภาพ", "arabic": "تفعيل", "russian": "Повышение эффективности"},
    {"kanji": "合理化", "kana": "ごうりか", "romaji": "gourika", "english": "Rationalization", "thai": "การทำให้เป็นเหตุเป็นผล", "arabic": "ترشيد", "russian": "Рационализация"},
    {"kanji": "自動化", "kana": "じどうか", "romaji": "jidouka", "english": "Automation", "thai": "การทำให้อัตโนมัติ", "arabic": "أتمتة", "russian": "Автоматизация"},
    {"kanji": "機械化", "kana": "きかいか", "romaji": "kikaika", "english": "Mechanization", "thai": "การใช้เครื่องจักร", "arabic": "ميكنة", "russian": "Механизация"},
    {"kanji": "電子化", "kana": "でんしか", "romaji": "denshika", "english": "Digitization", "thai": "การทำให้เป็นดิจิทัล", "arabic": "رقمنة", "russian": "Оцифровка"},
    {"kanji": "情報化", "kana": "じょうほうか", "romaji": "jouhouka", "english": "Informatization", "thai": "การทำให้เป็นข้อมูล", "arabic": "معلوماتية", "russian": "Информатизация"},
    {"kanji": "グローバル化", "kana": "グローバルか", "romaji": "guroobaru-ka", "english": "Globalization", "thai": "โลกาภิวัตน์", "arabic": "عولمة", "russian": "Глобализация"},
    {"kanji": "地域化", "kana": "ちいきか", "romaji": "chiikika", "english": "Localization", "thai": "การทำให้เป็นท้องถิ่น", "arabic": "أقلمة", "russian": "Локализация"},
    {"kanji": "国際化", "kana": "こくさいか", "romaji": "kokusaika", "english": "Internationalization", "thai": "นานาชาติ", "arabic": "تدويل", "russian": "Интернационализация"},
    {"kanji": "多国籍化", "kana": "たこくせきか", "romaji": "takokusekika", "english": "Multinationalization", "thai": "การเป็นข้ามชาติ", "arabic": "تعدد الجنسيات", "russian": "Мультинационализация"},
    {"kanji": "近代化", "kana": "きんだいか", "romaji": "kindaika", "english": "Modernization", "thai": "การทันสมัย", "arabic": "تحديث", "russian": "Модернизация"},
    {"kanji": "産業化", "kana": "さんぎょうか", "romaji": "sangyouka", "english": "Industrialization", "thai": "การอุตสาหกรรม", "arabic": "تصنيع", "russian": "Индустриализация"},
    {"kanji": "都市化", "kana": "としか", "romaji": "toshika", "english": "Urbanization", "thai": "การกลายเป็นเมือง", "arabic": "تحضر", "russian": "Урбанизация"},
    {"kanji": "民主化", "kana": "みんしゅか", "romaji": "minshuka", "english": "Democratization", "thai": "ประชาธิปไตย", "arabic": "دمقرطة", "russian": "Демократизация"},
    {"kanji": "市場化", "kana": "しじょうか", "romaji": "shijouka", "english": "Marketization", "thai": "การทำให้เป็นตลาด", "arabic": "تسويق", "russian": "Маркетизация"},
    {"kanji": "商業化", "kana": "しょうぎょうか", "romaji": "shougyouka", "english": "Commercialization", "thai": "การค้า", "arabic": "تجارة", "russian": "Коммерциализация"},
    {"kanji": "大衆化", "kana": "たいしゅうか", "romaji": "taishuuka", "english": "Popularization", "thai": "การทำให้เป็นที่นิยม", "arabic": "تعميم", "russian": "Популяризация"},
    {"kanji": "専門化", "kana": "せんもんか", "romaji": "senmonka", "english": "Professionalization", "thai": "การเป็นมืออาชีพ", "arabic": "احتراف", "russian": "Профессионализация"},
    {"kanji": "制度化", "kana": "せいどか", "romaji": "seidoka", "english": "Institutionalization", "thai": "การสถาบัน", "arabic": "مأسسة", "russian": "Институционализация"},
    {"kanji": "組織化", "kana": "そしきか", "romaji": "soshikika", "english": "Organization", "thai": "การจัดองค์กร", "arabic": "تنظيم", "russian": "Организация"},
    {"kanji": "構造化", "kana": "こうぞうか", "romaji": "kouzouka", "english": "Structuring", "thai": "การจัดโครงสร้าง", "arabic": "هيكلة", "russian": "Структурирование"},
    {"kanji": "階層化", "kana": "かいそうか", "romaji": "kaisouka", "english": "Stratification", "thai": "การแบ่งชั้น", "arabic": "تطبق", "russian": "Стратификация"},
    {"kanji": "細分化", "kana": "さいぶんか", "romaji": "saibunka", "english": "Subdivision", "thai": "การแบ่งย่อย", "arabic": "تقسيم", "russian": "Подразделение"},
    {"kanji": "統合化", "kana": "とうごうか", "romaji": "tougouka", "english": "Integration", "thai": "การรวม", "arabic": "تكامل", "russian": "Интеграция"},
    {"kanji": "分権化", "kana": "ぶんけんか", "romaji": "bunkenka", "english": "Decentralization", "thai": "การกระจายอำนาจ", "arabic": "لامركزية", "russian": "Децентрализация"},
    {"kanji": "集権化", "kana": "しゅうけんか", "romaji": "shuukenka", "english": "Centralization", "thai": "การรวมอำนาจ", "arabic": "مركزية", "russian": "Централизация"},
    {"kanji": "民営化", "kana": "みんえいか", "romaji": "min'eika", "english": "Privatization", "thai": "การแปรรูป", "arabic": "خصخصة", "russian": "Приватизация"},
    {"kanji": "国有化", "kana": "こくゆうか", "romaji": "kokuyuuka", "english": "Nationalization", "thai": "การทำให้เป็นของรัฐ", "arabic": "تأميم", "russian": "Национализация"},
    {"kanji": "世俗化", "kana": "せぞくか", "romaji": "sezokuka", "english": "Secularization", "thai": "ความเป็นฆราวาส", "arabic": "علمنة", "russian": "Секуляризация"}
]
