# Japanese Vocabulary Database - Part 3 (Words 401-600)

VOCAB_PART3 = [
    # Relationships & Society (401-430)
    {"kanji": "関係", "kana": "かんけい", "romaji": "kankei", "english": "Relationship", "thai": "ความสัมพันธ์", "arabic": "علاقة", "russian": "Отношение"},
    {"kanji": "親密", "kana": "しんみつ", "romaji": "shinmitsu", "english": "Intimacy", "thai": "ความใกล้ชิด", "arabic": "حميمية", "russian": "Близость"},
    {"kanji": "疎遠", "kana": "そえん", "romaji": "soen", "english": "Estrangement", "thai": "ความห่างเหิน", "arabic": "جفاء", "russian": "Отчуждение"},
    {"kanji": "協力", "kana": "きょうりょく", "romaji": "kyouryoku", "english": "Cooperation", "thai": "ความร่วมมือ", "arabic": "تعاون", "russian": "Сотрудничество"},
    {"kanji": "対立", "kana": "たいりつ", "romaji": "tairitsu", "english": "Opposition", "thai": "การต่อต้าน", "arabic": "معارضة", "russian": "Противостояние"},
    {"kanji": "依存", "kana": "いぞん", "romaji": "izon", "english": "Dependence", "thai": "การพึ่งพา", "arabic": "اعتماد", "russian": "Зависимость"},
    {"kanji": "独立", "kana": "どくりつ", "romaji": "dokuritsu", "english": "Independence", "thai": "เอกราช", "arabic": "استقلال", "russian": "Независимость"},
    {"kanji": "孤立", "kana": "こりつ", "romaji": "koritsu", "english": "Isolation", "thai": "ความโดดเดี่ยว", "arabic": "عزلة", "russian": "Изоляция"},
    {"kanji": "統合", "kana": "とうごう", "romaji": "tougou", "english": "Integration", "thai": "การรวม", "arabic": "تكامل", "russian": "Интеграция"},
    {"kanji": "分裂", "kana": "ぶんれつ", "romaji": "bunretsu", "english": "Division", "thai": "การแตกแยก", "arabic": "انقسام", "russian": "Раскол"},
    {"kanji": "団結", "kana": "だんけつ", "romaji": "danketsu", "english": "Unity", "thai": "ความสามัคคี", "arabic": "وحدة", "russian": "Единство"},
    {"kanji": "連帯", "kana": "れんたい", "romaji": "rentai", "english": "Solidarity", "thai": "ความเป็นน้ำหนึ่งใจเดียวกัน", "arabic": "تضامن", "russian": "Солидарность"},
    {"kanji": "信頼", "kana": "しんらい", "romaji": "shinrai", "english": "Trust", "thai": "ความไว้วางใจ", "arabic": "ثقة", "russian": "Доверие"},
    {"kanji": "不信", "kana": "ふしん", "romaji": "fushin", "english": "Distrust", "thai": "ความไม่ไว้วางใจ", "arabic": "عدم ثقة", "russian": "Недоверие"},
    {"kanji": "忠誠", "kana": "ちゅうせい", "romaji": "chuusei", "english": "Loyalty", "thai": "ความจงรักภักดี", "arabic": "ولاء", "russian": "Верность"},
    {"kanji": "裏切り", "kana": "うらぎり", "romaji": "uragiri", "english": "Betrayal", "thai": "การทรยศ", "arabic": "خيانة", "russian": "Предательство"},
    {"kanji": "献身", "kana": "けんしん", "romaji": "kenshin", "english": "Devotion", "thai": "การอุทิศตน", "arabic": "تفاني", "russian": "Преданность"},
    {"kanji": "犠牲", "kana": "ぎせい", "romaji": "gisei", "english": "Sacrifice", "thai": "การเสียสละ", "arabic": "تضحية", "russian": "Жертва"},
    {"kanji": "貢献", "kana": "こうけん", "romaji": "kouken", "english": "Contribution", "thai": "การมีส่วนร่วม", "arabic": "مساهمة", "russian": "Вклад"},
    {"kanji": "搾取", "kana": "さくしゅ", "romaji": "sakushu", "english": "Exploitation", "thai": "การแสวงหาประโยชน์", "arabic": "استغلال", "russian": "Эксплуатация"},
    {"kanji": "支配", "kana": "しはい", "romaji": "shihai", "english": "Domination", "thai": "การปกครอง", "arabic": "هيمنة", "russian": "Господство"},
    {"kanji": "服従", "kana": "ふくじゅう", "romaji": "fukujuu", "english": "Obedience", "thai": "ความเชื่อฟัง", "arabic": "طاعة", "russian": "Послушание"},
    {"kanji": "反抗", "kana": "はんこう", "romaji": "hankou", "english": "Rebellion", "thai": "การกบฏ", "arabic": "تمرد", "russian": "Бунт"},
    {"kanji": "抵抗", "kana": "ていこう", "romaji": "teikou", "english": "Resistance", "thai": "การต่อต้าน", "arabic": "مقاومة", "russian": "Сопротивление"},
    {"kanji": "屈服", "kana": "くっぷく", "romaji": "kuppuku", "english": "Submission", "thai": "การยอมจำนน", "arabic": "خضوع", "russian": "Подчинение"},
    {"kanji": "譲歩", "kana": "じょうほ", "romaji": "jouho", "english": "Concession", "thai": "การยอม", "arabic": "تنازل", "russian": "Уступка"},
    {"kanji": "妥協", "kana": "だきょう", "romaji": "dakyou", "english": "Compromise", "thai": "ประนีประนอม", "arabic": "تسوية", "russian": "Компромисс"},
    {"kanji": "交渉", "kana": "こうしょう", "romaji": "koushou", "english": "Negotiation", "thai": "การเจรจา", "arabic": "تفاوض", "russian": "Переговоры"},
    {"kanji": "調停", "kana": "ちょうてい", "romaji": "choutei", "english": "Mediation", "thai": "การไกล่เกลี่ย", "arabic": "وساطة", "russian": "Посредничество"},
    {"kanji": "和解", "kana": "わかい", "romaji": "wakai", "english": "Reconciliation", "thai": "การคืนดี", "arabic": "مصالحة", "russian": "Примирение"},

    # Communication & Expression (431-460)
    {"kanji": "伝達", "kana": "でんたつ", "romaji": "dentatsu", "english": "Conveyance", "thai": "การส่งต่อ", "arabic": "إيصال", "russian": "Передача"},
    {"kanji": "意思疎通", "kana": "いしそつう", "romaji": "ishisotsuu", "english": "Communication", "thai": "การสื่อสาร", "arabic": "تواصل", "russian": "Общение"},
    {"kanji": "対話", "kana": "たいわ", "romaji": "taiwa", "english": "Dialogue", "thai": "การสนทนา", "arabic": "حوار", "russian": "Диалог"},
    {"kanji": "独白", "kana": "どくはく", "romaji": "dokuhaku", "english": "Monologue", "thai": "บทพูดคนเดียว", "arabic": "مونولوج", "russian": "Монолог"},
    {"kanji": "会話", "kana": "かいわ", "romaji": "kaiwa", "english": "Conversation", "thai": "การสนทนา", "arabic": "محادثة", "russian": "Разговор"},
    {"kanji": "演説", "kana": "えんぜつ", "romaji": "enzetsu", "english": "Speech", "thai": "การกล่าวสุนทรพจน์", "arabic": "خطاب", "russian": "Речь"},
    {"kanji": "弁論", "kana": "べんろん", "romaji": "benron", "english": "Oratory", "thai": "การโต้แย้ง", "arabic": "خطابة", "russian": "Ораторство"},
    {"kanji": "陳述", "kana": "ちんじゅつ", "romaji": "chinjutsu", "english": "Statement", "thai": "การแถลง", "arabic": "بيان", "russian": "Изложение"},
    {"kanji": "主張", "kana": "しゅちょう", "romaji": "shuchou", "english": "Assertion", "thai": "การยืนยัน", "arabic": "ادعاء", "russian": "Утверждение"},
    {"kanji": "反論", "kana": "はんろん", "romaji": "hanron", "english": "Rebuttal", "thai": "การโต้แย้ง", "arabic": "دحض", "russian": "Опровержение"},
    {"kanji": "説得", "kana": "せっとく", "romaji": "settoku", "english": "Persuasion", "thai": "การโน้มน้าว", "arabic": "إقناع", "russian": "Убеждение"},
    {"kanji": "納得", "kana": "なっとく", "romaji": "nattoku", "english": "Acceptance", "thai": "ความเข้าใจ", "arabic": "اقتناع", "russian": "Согласие"},
    {"kanji": "拒否", "kana": "きょひ", "romaji": "kyohi", "english": "Refusal", "thai": "การปฏิเสธ", "arabic": "رفض", "russian": "Отказ"},
    {"kanji": "承認", "kana": "しょうにん", "romaji": "shounin", "english": "Approval", "thai": "การอนุมัติ", "arabic": "موافقة", "russian": "Одобрение"},
    {"kanji": "否認", "kana": "ひにん", "romaji": "hinin", "english": "Denial", "thai": "การปฏิเสธ", "arabic": "إنكار", "russian": "Отрицание"},
    {"kanji": "同意", "kana": "どうい", "romaji": "doui", "english": "Consent", "thai": "ความยินยอม", "arabic": "موافقة", "russian": "Согласие"},
    {"kanji": "異議", "kana": "いぎ", "romaji": "igi", "english": "Objection", "thai": "ข้อโต้แย้ง", "arabic": "اعتراض", "russian": "Возражение"},
    {"kanji": "賛成", "kana": "さんせい", "romaji": "sansei", "english": "Agreement", "thai": "การเห็นด้วย", "arabic": "اتفاق", "russian": "Одобрение"},
    {"kanji": "反対", "kana": "はんたい", "romaji": "hantai", "english": "Opposition", "thai": "การคัดค้าน", "arabic": "معارضة", "russian": "Противопоставление"},
    {"kanji": "肯定", "kana": "こうてい", "romaji": "koutei", "english": "Affirmation", "thai": "การยืนยัน", "arabic": "تأكيد", "russian": "Утверждение"},
    {"kanji": "否定", "kana": "ひてい", "romaji": "hitei", "english": "Negation", "thai": "การปฏิเสธ", "arabic": "نفي", "russian": "Отрицание"},
    {"kanji": "暗示", "kana": "あんじ", "romaji": "anji", "english": "Implication", "thai": "การบอกเป็นนัย", "arabic": "تلميح", "russian": "Намёк"},
    {"kanji": "明示", "kana": "めいじ", "romaji": "meiji", "english": "Explicit", "thai": "ชัดเจน", "arabic": "صريح", "russian": "Явный"},
    {"kanji": "示唆", "kana": "しさ", "romaji": "shisa", "english": "Suggestion", "thai": "ข้อเสนอแนะ", "arabic": "اقتراح", "russian": "Намёк"},
    {"kanji": "言及", "kana": "げんきゅう", "romaji": "genkyuu", "english": "Mention", "thai": "การกล่าวถึง", "arabic": "إشارة", "russian": "Упоминание"},
    {"kanji": "言明", "kana": "げんめい", "romaji": "genmei", "english": "Declaration", "thai": "การประกาศ", "arabic": "تصريح", "russian": "Заявление"},
    {"kanji": "発言", "kana": "はつげん", "romaji": "hatsugen", "english": "Remark", "thai": "ความเห็น", "arabic": "تعليق", "russian": "Высказывание"},
    {"kanji": "沈黙", "kana": "ちんもく", "romaji": "chinmoku", "english": "Silence", "thai": "ความเงียบ", "arabic": "صمت", "russian": "Молчание"},
    {"kanji": "雄弁", "kana": "ゆうべん", "romaji": "yuuben", "english": "Eloquence", "thai": "การพูดคล่อง", "arabic": "فصاحة", "russian": "Красноречие"},
    {"kanji": "無口", "kana": "むくち", "romaji": "mukuchi", "english": "Taciturn", "thai": "เงียบขรึม", "arabic": "كتوم", "russian": "Молчаливый"},

    # Cognition & Thinking (461-490)
    {"kanji": "思考", "kana": "しこう", "romaji": "shikou", "english": "Thinking", "thai": "การคิด", "arabic": "تفكير", "russian": "Мышление"},
    {"kanji": "考察", "kana": "こうさつ", "romaji": "kousatsu", "english": "Consideration", "thai": "การพิจารณา", "arabic": "تأمل", "russian": "Размышление"},
    {"kanji": "熟考", "kana": "じゅっこう", "romaji": "jukkou", "english": "Deliberation", "thai": "การคิดพิจารณา", "arabic": "تفكير عميق", "russian": "Обдумывание"},
    {"kanji": "瞑想", "kana": "めいそう", "romaji": "meisou", "english": "Meditation", "thai": "การทำสมาธิ", "arabic": "تأمل", "russian": "Медитация"},
    {"kanji": "想像", "kana": "そうぞう", "romaji": "souzou", "english": "Imagination", "thai": "จินตนาการ", "arabic": "خيال", "russian": "Воображение"},
    {"kanji": "空想", "kana": "くうそう", "romaji": "kuusou", "english": "Fantasy", "thai": "จินตนาการ", "arabic": "وهم", "russian": "Фантазия"},
    {"kanji": "妄想", "kana": "もうそう", "romaji": "mousou", "english": "Delusion", "thai": "ความหลงผิด", "arabic": "توهم", "russian": "Бред"},
    {"kanji": "錯覚", "kana": "さっかく", "romaji": "sakkaku", "english": "Illusion", "thai": "ภาพลวงตา", "arabic": "وهم", "russian": "Иллюзия"},
    {"kanji": "幻覚", "kana": "げんかく", "romaji": "genkaku", "english": "Hallucination", "thai": "ภาพหลอน", "arabic": "هلوسة", "russian": "Галлюцинация"},
    {"kanji": "錯誤", "kana": "さくご", "romaji": "sakugo", "english": "Error", "thai": "ความผิดพลาด", "arabic": "خطأ", "russian": "Ошибка"},
    {"kanji": "誤解", "kana": "ごかい", "romaji": "gokai", "english": "Misunderstanding", "thai": "ความเข้าใจผิด", "arabic": "سوء فهم", "russian": "Недоразумение"},
    {"kanji": "理解", "kana": "りかい", "romaji": "rikai", "english": "Comprehension", "thai": "ความเข้าใจ", "arabic": "فهم", "russian": "Понимание"},
    {"kanji": "了解", "kana": "りょうかい", "romaji": "ryoukai", "english": "Acknowledgment", "thai": "การรับทราบ", "arabic": "إدراك", "russian": "Понимание"},
    {"kanji": "無知", "kana": "むち", "romaji": "muchi", "english": "Ignorance", "thai": "ความไม่รู้", "arabic": "جهل", "russian": "Невежество"},
    {"kanji": "博識", "kana": "はくしき", "romaji": "hakushiki", "english": "Erudition", "thai": "ความรอบรู้", "arabic": "معرفة", "russian": "Эрудиция"},
    {"kanji": "洞察", "kana": "どうさつ", "romaji": "dousatsu", "english": "Insight", "thai": "ความเข้าใจลึกซึ้ง", "arabic": "بصيرة", "russian": "Проницательность"},
    {"kanji": "先見", "kana": "せんけん", "romaji": "senken", "english": "Foresight", "thai": "การมองการณ์ไกล", "arabic": "بصيرة", "russian": "Предвидение"},
    {"kanji": "盲目", "kana": "もうもく", "romaji": "moumoku", "english": "Blindness", "thai": "ความตาบอด", "arabic": "عمى", "russian": "Слепота"},
    {"kanji": "明察", "kana": "めいさつ", "romaji": "meisatsu", "english": "Discernment", "thai": "ความเฉียบแหลม", "arabic": "فراسة", "russian": "Проницательность"},
    {"kanji": "鈍感", "kana": "どんかん", "romaji": "donkan", "english": "Insensitivity", "thai": "ความไม่ไว", "arabic": "بلادة", "russian": "Нечувствительность"},
    {"kanji": "敏感", "kana": "びんかん", "romaji": "binkan", "english": "Sensitivity", "thai": "ความไว", "arabic": "حساسية", "russian": "Чувствительность"},
    {"kanji": "注意", "kana": "ちゅうい", "romaji": "chuui", "english": "Attention", "thai": "ความใส่ใจ", "arabic": "انتباه", "russian": "Внимание"},
    {"kanji": "集中", "kana": "しゅうちゅう", "romaji": "shuuchuu", "english": "Concentration", "thai": "การมุ่งความสนใจ", "arabic": "تركيز", "russian": "Концентрация"},
    {"kanji": "散漫", "kana": "さんまん", "romaji": "sanman", "english": "Distraction", "thai": "ความฟุ้งซ่าน", "arabic": "تشتت", "russian": "Рассеянность"},
    {"kanji": "覚醒", "kana": "かくせい", "romaji": "kakusei", "english": "Awakening", "thai": "การตื่นรู้", "arabic": "يقظة", "russian": "Пробуждение"},
    {"kanji": "鋭敏", "kana": "えいびん", "romaji": "eibin", "english": "Acuteness", "thai": "ความแหลมคม", "arabic": "حدة", "russian": "Острота"},
    {"kanji": "鈍麻", "kana": "どんま", "romaji": "donma", "english": "Dullness", "thai": "ความทึบ", "arabic": "خدر", "russian": "Притупление"},
    {"kanji": "明晰", "kana": "めいせき", "romaji": "meiseki", "english": "Clarity", "thai": "ความชัดเจน", "arabic": "وضوح", "russian": "Ясность"},
    {"kanji": "混乱", "kana": "こんらん", "romaji": "konran", "english": "Confusion", "thai": "ความสับสน", "arabic": "ارتباك", "russian": "Путаница"},
    {"kanji": "整理", "kana": "せいり", "romaji": "seiri", "english": "Organization", "thai": "การจัดระเบียบ", "arabic": "ترتيب", "russian": "Организация"},

    # Action & Movement (491-520)
    {"kanji": "行動", "kana": "こうどう", "romaji": "koudou", "english": "Action", "thai": "การกระทำ", "arabic": "عمل", "russian": "Действие"},
    {"kanji": "実行", "kana": "じっこう", "romaji": "jikkou", "english": "Execution", "thai": "การดำเนินการ", "arabic": "تنفيذ", "russian": "Выполнение"},
    {"kanji": "遂行", "kana": "すいこう", "romaji": "suikou", "english": "Performance", "thai": "การปฏิบัติ", "arabic": "إنجاز", "russian": "Исполнение"},
    {"kanji": "運動", "kana": "うんどう", "romaji": "undou", "english": "Movement", "thai": "การเคลื่อนไหว", "arabic": "حركة", "russian": "Движение"},
    {"kanji": "静止", "kana": "せいし", "romaji": "seishi", "english": "Stillness", "thai": "ความนิ่ง", "arabic": "سكون", "russian": "Неподвижность"},
    {"kanji": "活動", "kana": "かつどう", "romaji": "katsudou", "english": "Activity", "thai": "กิจกรรม", "arabic": "نشاط", "russian": "Деятельность"},
    {"kanji": "休止", "kana": "きゅうし", "romaji": "kyuushi", "english": "Pause", "thai": "การหยุด", "arabic": "توقف", "russian": "Пауза"},
    {"kanji": "進行", "kana": "しんこう", "romaji": "shinkou", "english": "Progression", "thai": "ความก้าวหน้า", "arabic": "تقدم", "russian": "Прогресс"},
    {"kanji": "後退", "kana": "こうたい", "romaji": "koutai", "english": "Retreat", "thai": "การถอย", "arabic": "تراجع", "russian": "Отступление"},
    {"kanji": "前進", "kana": "ぜんしん", "romaji": "zenshin", "english": "Advance", "thai": "การก้าวไปข้างหน้า", "arabic": "تقدم", "russian": "Продвижение"},
    {"kanji": "停滞", "kana": "ていたい", "romaji": "teitai", "english": "Stagnation", "thai": "ความซบเซา", "arabic": "ركود", "russian": "Застой"},
    {"kanji": "飛躍", "kana": "ひやく", "romaji": "hiyaku", "english": "Leap", "thai": "การก้าวกระโดด", "arabic": "قفزة", "russian": "Скачок"},
    {"kanji": "跳躍", "kana": "ちょうやく", "romaji": "chouyaku", "english": "Jump", "thai": "การกระโดด", "arabic": "قفز", "russian": "Прыжок"},
    {"kanji": "転落", "kana": "てんらく", "romaji": "tenraku", "english": "Fall", "thai": "การตกลง", "arabic": "سقوط", "russian": "Падение"},
    {"kanji": "上昇", "kana": "じょうしょう", "romaji": "joushou", "english": "Rise", "thai": "การขึ้น", "arabic": "صعود", "russian": "Подъём"},
    {"kanji": "下降", "kana": "かこう", "romaji": "kakou", "english": "Descent", "thai": "การลง", "arabic": "هبوط", "russian": "Спуск"},
    {"kanji": "回転", "kana": "かいてん", "romaji": "kaiten", "english": "Rotation", "thai": "การหมุน", "arabic": "دوران", "russian": "Вращение"},
    {"kanji": "旋回", "kana": "せんかい", "romaji": "senkai", "english": "Revolution", "thai": "การโคจร", "arabic": "دوران", "russian": "Оборот"},
    {"kanji": "振動", "kana": "しんどう", "romaji": "shindou", "english": "Vibration", "thai": "การสั่นสะเทือน", "arabic": "اهتزاز", "russian": "Вибрация"},
    {"kanji": "動揺", "kana": "どうよう", "romaji": "douyou", "english": "Fluctuation", "thai": "ความสั่นคลอน", "arabic": "اضطراب", "russian": "Колебание"},
    {"kanji": "安定", "kana": "あんてい", "romaji": "antei", "english": "Stability", "thai": "ความมั่นคง", "arabic": "استقرار", "russian": "Стабильность"},
    {"kanji": "不安定", "kana": "ふあんてい", "romaji": "fuantei", "english": "Instability", "thai": "ความไม่มั่นคง", "arabic": "عدم استقرار", "russian": "Нестабильность"},
    {"kanji": "平衡", "kana": "へいこう", "romaji": "heikou", "english": "Equilibrium", "thai": "สมดุล", "arabic": "توازن", "russian": "Равновесие"},
    {"kanji": "傾斜", "kana": "けいしゃ", "romaji": "keisha", "english": "Inclination", "thai": "ความลาดเอียง", "arabic": "ميل", "russian": "Наклон"},
    {"kanji": "接近", "kana": "せっきん", "romaji": "sekkin", "english": "Approach", "thai": "การเข้าใกล้", "arabic": "اقتراب", "russian": "Приближение"},
    {"kanji": "離脱", "kana": "りだつ", "romaji": "ridatsu", "english": "Separation", "thai": "การแยก", "arabic": "انفصال", "russian": "Отделение"},
    {"kanji": "接触", "kana": "せっしょく", "romaji": "sesshoku", "english": "Contact", "thai": "การสัมผัส", "arabic": "اتصال", "russian": "Контакт"},
    {"kanji": "衝突", "kana": "しょうとつ", "romaji": "shoutotsu", "english": "Collision", "thai": "การชน", "arabic": "تصادم", "russian": "Столкновение"},
    {"kanji": "融合", "kana": "ゆうごう", "romaji": "yuugou", "english": "Fusion", "thai": "การรวมตัว", "arabic": "اندماج", "russian": "Слияние"},
    {"kanji": "分離", "kana": "ぶんり", "romaji": "bunri", "english": "Separation", "thai": "การแยก", "arabic": "فصل", "russian": "Разделение"},

    # Cause & Effect (521-550)
    {"kanji": "原因", "kana": "げんいん", "romaji": "gen'in", "english": "Cause", "thai": "สาเหตุ", "arabic": "سبب", "russian": "Причина"},
    {"kanji": "結果", "kana": "けっか", "romaji": "kekka", "english": "Result", "thai": "ผลลัพธ์", "arabic": "نتيجة", "russian": "Результат"},
    {"kanji": "要因", "kana": "よういん", "romaji": "youin", "english": "Factor", "thai": "ปัจจัย", "arabic": "عامل", "russian": "Фактор"},
    {"kanji": "帰結", "kana": "きけつ", "romaji": "kiketsu", "english": "Consequence", "thai": "ผลที่ตามมา", "arabic": "عاقبة", "russian": "Последствие"},
    {"kanji": "誘因", "kana": "ゆういん", "romaji": "yuuin", "english": "Inducement", "thai": "สิ่งกระตุ้น", "arabic": "محفز", "russian": "Побуждение"},
    {"kanji": "作用", "kana": "さよう", "romaji": "sayou", "english": "Effect", "thai": "ผลกระทบ", "arabic": "تأثير", "russian": "Действие"},
    {"kanji": "影響", "kana": "えいきょう", "romaji": "eikyou", "english": "Influence", "thai": "อิทธิพล", "arabic": "تأثير", "russian": "Влияние"},
    {"kanji": "反応", "kana": "はんのう", "romaji": "hannou", "english": "Response", "thai": "การตอบสนอง", "arabic": "استجابة", "russian": "Реакция"},
    {"kanji": "刺激", "kana": "しげき", "romaji": "shigeki", "english": "Stimulus", "thai": "สิ่งกระตุ้น", "arabic": "تحفيز", "russian": "Стимул"},
    {"kanji": "誘発", "kana": "ゆうはつ", "romaji": "yuuhatsu", "english": "Induction", "thai": "การกระตุ้น", "arabic": "تحريض", "russian": "Побуждение"},
    {"kanji": "抑制", "kana": "よくせい", "romaji": "yokusei", "english": "Inhibition", "thai": "การยับยั้ง", "arabic": "كبح", "russian": "Сдерживание"},
    {"kanji": "促進", "kana": "そくしん", "romaji": "sokushin", "english": "Promotion", "thai": "การส่งเสริม", "arabic": "تعزيز", "russian": "Продвижение"},
    {"kanji": "阻害", "kana": "そがい", "romaji": "sogai", "english": "Hindrance", "thai": "การขัดขวาง", "arabic": "إعاقة", "russian": "Препятствие"},
    {"kanji": "助長", "kana": "じょちょう", "romaji": "jochou", "english": "Encouragement", "thai": "การสนับสนุน", "arabic": "تشجيع", "russian": "Поощрение"},
    {"kanji": "妨害", "kana": "ぼうがい", "romaji": "bougai", "english": "Obstruction", "thai": "การกีดขวาง", "arabic": "عرقلة", "russian": "Помеха"},
    {"kanji": "貢献", "kana": "こうけん", "romaji": "kouken", "english": "Contribution", "thai": "การสนับสนุน", "arabic": "مساهمة", "russian": "Вклад"},
    {"kanji": "悪化", "kana": "あっか", "romaji": "akka", "english": "Deterioration", "thai": "การเลวลง", "arabic": "تدهور", "russian": "Ухудшение"},
    {"kanji": "改善", "kana": "かいぜん", "romaji": "kaizen", "english": "Improvement", "thai": "การปรับปรุง", "arabic": "تحسين", "russian": "Улучшение"},
    {"kanji": "強化", "kana": "きょうか", "romaji": "kyouka", "english": "Reinforcement", "thai": "การเสริมกำลัง", "arabic": "تعزيز", "russian": "Усиление"},
    {"kanji": "弱化", "kana": "じゃっか", "romaji": "jakka", "english": "Weakening", "thai": "การทำให้อ่อนแอ", "arabic": "إضعاف", "russian": "Ослабление"},
    {"kanji": "激化", "kana": "げきか", "romaji": "gekika", "english": "Intensification", "thai": "การรุนแรงขึ้น", "arabic": "تصعيد", "russian": "Обострение"},
    {"kanji": "緩和", "kana": "かんわ", "romaji": "kanwa", "english": "Mitigation", "thai": "การบรรเทา", "arabic": "تخفيف", "russian": "Смягчение"},
    {"kanji": "拡大", "kana": "かくだい", "romaji": "kakudai", "english": "Expansion", "thai": "การขยาย", "arabic": "توسيع", "russian": "Расширение"},
    {"kanji": "縮小", "kana": "しゅくしょう", "romaji": "shukushou", "english": "Reduction", "thai": "การหด", "arabic": "تقليص", "russian": "Сокращение"},
    {"kanji": "延長", "kana": "えんちょう", "romaji": "enchou", "english": "Extension", "thai": "การขยายเวลา", "arabic": "تمديد", "russian": "Продление"},
    {"kanji": "短縮", "kana": "たんしゅく", "romaji": "tanshuku", "english": "Shortening", "thai": "การลด", "arabic": "اختصار", "russian": "Сокращение"},
    {"kanji": "深化", "kana": "しんか", "romaji": "shinka", "english": "Deepening", "thai": "การทำให้ลึกซึ้ง", "arabic": "تعميق", "russian": "Углубление"},
    {"kanji": "浅化", "kana": "せんか", "romaji": "senka", "english": "Shallowing", "thai": "การทำให้ตื้น", "arabic": "تسطيح", "russian": "Обмеление"},
    {"kanji": "複雑化", "kana": "ふくざつか", "romaji": "fukuzatsuka", "english": "Complication", "thai": "การซับซ้อน", "arabic": "تعقيد", "russian": "Усложнение"},
    {"kanji": "単純化", "kana": "たんじゅんか", "romaji": "tanjunka", "english": "Simplification", "thai": "การทำให้ง่าย", "arabic": "تبسيط", "russian": "Упрощение"},

    # Existence & Being (551-580)
    {"kanji": "存在", "kana": "そんざい", "romaji": "sonzai", "english": "Existence", "thai": "การมีอยู่", "arabic": "وجود", "russian": "Существование"},
    {"kanji": "不在", "kana": "ふざい", "romaji": "fuzai", "english": "Absence", "thai": "ความไม่อยู่", "arabic": "غياب", "russian": "Отсутствие"},
    {"kanji": "実在", "kana": "じつざい", "romaji": "jitsuzai", "english": "Reality", "thai": "ความเป็นจริง", "arabic": "واقع", "russian": "Реальность"},
    {"kanji": "虚無", "kana": "きょむ", "romaji": "kyomu", "english": "Nothingness", "thai": "ความว่างเปล่า", "arabic": "عدم", "russian": "Небытие"},
    {"kanji": "生存", "kana": "せいぞん", "romaji": "seizon", "english": "Survival", "thai": "การอยู่รอด", "arabic": "بقاء", "russian": "Выживание"},
    {"kanji": "消滅", "kana": "しょうめつ", "romaji": "shoumetsu", "english": "Extinction", "thai": "การสูญสลาย", "arabic": "انقراض", "russian": "Исчезновение"},
    {"kanji": "発生", "kana": "はっせい", "romaji": "hassei", "english": "Occurrence", "thai": "การเกิดขึ้น", "arabic": "حدوث", "russian": "Возникновение"},
    {"kanji": "消失", "kana": "しょうしつ", "romaji": "shoushitsu", "english": "Disappearance", "thai": "การหายไป", "arabic": "اختفاء", "russian": "Исчезновение"},
    {"kanji": "誕生", "kana": "たんじょう", "romaji": "tanjou", "english": "Birth", "thai": "การเกิด", "arabic": "ميلاد", "russian": "Рождение"},
    {"kanji": "死亡", "kana": "しぼう", "romaji": "shibou", "english": "Death", "thai": "ความตาย", "arabic": "وفاة", "russian": "Смерть"},
    {"kanji": "出現", "kana": "しゅつげん", "romaji": "shutsugen", "english": "Appearance", "thai": "การปรากฏ", "arabic": "ظهور", "russian": "Появление"},
    {"kanji": "隠滅", "kana": "いんめつ", "romaji": "inmetsu", "english": "Concealment", "thai": "การซ่อนเร้น", "arabic": "إخفاء", "russian": "Сокрытие"},
    {"kanji": "顕現", "kana": "けんげん", "romaji": "kengen", "english": "Manifestation", "thai": "การแสดงออก", "arabic": "تجلي", "russian": "Проявление"},
    {"kanji": "潜伏", "kana": "せんぷく", "romaji": "senpuku", "english": "Latency", "thai": "การแอบซ่อน", "arabic": "كمون", "russian": "Скрытность"},
    {"kanji": "露出", "kana": "ろしゅつ", "romaji": "roshutsu", "english": "Exposure", "thai": "การเปิดเผย", "arabic": "تعرض", "russian": "Обнажение"},
    {"kanji": "存続", "kana": "そんぞく", "romaji": "sonzoku", "english": "Continuation", "thai": "การดำรงอยู่", "arabic": "استمرار", "russian": "Продолжение"},
    {"kanji": "中止", "kana": "ちゅうし", "romaji": "chuushi", "english": "Suspension", "thai": "การยกเลิก", "arabic": "إيقاف", "russian": "Прекращение"},
    {"kanji": "維持", "kana": "いじ", "romaji": "iji", "english": "Maintenance", "thai": "การรักษา", "arabic": "صيانة", "russian": "Поддержание"},
    {"kanji": "廃止", "kana": "はいし", "romaji": "haishi", "english": "Abolition", "thai": "การยกเลิก", "arabic": "إلغاء", "russian": "Упразднение"},
    {"kanji": "保持", "kana": "ほじ", "romaji": "hoji", "english": "Retention", "thai": "การเก็บรักษา", "arabic": "احتفاظ", "russian": "Сохранение"},
    {"kanji": "喪失", "kana": "そうしつ", "romaji": "soushitsu", "english": "Loss", "thai": "การสูญเสีย", "arabic": "فقدان", "russian": "Утрата"},
    {"kanji": "獲得", "kana": "かくとく", "romaji": "kakutoku", "english": "Acquisition", "thai": "การได้มา", "arabic": "اكتساب", "russian": "Приобретение"},
    {"kanji": "所有", "kana": "しょゆう", "romaji": "shoyuu", "english": "Possession", "thai": "การครอบครอง", "arabic": "امتلاك", "russian": "Владение"},
    {"kanji": "欠乏", "kana": "けつぼう", "romaji": "ketsubou", "english": "Deficiency", "thai": "ความขาดแคลน", "arabic": "نقص", "russian": "Недостаток"},
    {"kanji": "充実", "kana": "じゅうじつ", "romaji": "juujitsu", "english": "Fulfillment", "thai": "ความสมบูรณ์", "arabic": "اكتمال", "russian": "Наполнение"},
    {"kanji": "空虚", "kana": "くうきょ", "romaji": "kuukyo", "english": "Emptiness", "thai": "ความว่างเปล่า", "arabic": "فراغ", "russian": "Пустота"},
    {"kanji": "充満", "kana": "じゅうまん", "romaji": "juuman", "english": "Fullness", "thai": "ความเต็ม", "arabic": "امتلاء", "russian": "Наполненность"},
    {"kanji": "枯渇", "kana": "こかつ", "romaji": "kokatsu", "english": "Exhaustion", "thai": "ความหมดสิ้น", "arabic": "نضوب", "russian": "Истощение"},
    {"kanji": "飽和", "kana": "ほうわ", "romaji": "houwa", "english": "Saturation", "thai": "ความอิ่มตัว", "arabic": "تشبع", "russian": "Насыщение"},
    {"kanji": "欠如", "kana": "けつじょ", "romaji": "ketsujo", "english": "Lack", "thai": "การขาด", "arabic": "انعدام", "russian": "Отсутствие"},

    # States & Conditions (581-600)
    {"kanji": "状態", "kana": "じょうたい", "romaji": "joutai", "english": "State", "thai": "สถานะ", "arabic": "حالة", "russian": "Состояние"},
    {"kanji": "状況", "kana": "じょうきょう", "romaji": "joukyou", "english": "Situation", "thai": "สถานการณ์", "arabic": "موقف", "russian": "Ситуация"},
    {"kanji": "事態", "kana": "じたい", "romaji": "jitai", "english": "Circumstance", "thai": "เหตุการณ์", "arabic": "ظرف", "russian": "Обстоятельство"},
    {"kanji": "局面", "kana": "きょくめん", "romaji": "kyokumen", "english": "Phase", "thai": "ระยะ", "arabic": "مرحلة", "russian": "Фаза"},
    {"kanji": "段階", "kana": "だんかい", "romaji": "dankai", "english": "Stage", "thai": "ขั้นตอน", "arabic": "مرحلة", "russian": "Этап"},
    {"kanji": "過程", "kana": "かてい", "romaji": "katei", "english": "Process", "thai": "กระบวนการ", "arabic": "عملية", "russian": "Процесс"},
    {"kanji": "経過", "kana": "けいか", "romaji": "keika", "english": "Progress", "thai": "ความคืบหน้า", "arabic": "مرور", "russian": "Течение"},
    {"kanji": "推移", "kana": "すいい", "romaji": "suii", "english": "Transition", "thai": "การเปลี่ยนผ่าน", "arabic": "تحول", "russian": "Переход"},
    {"kanji": "転換", "kana": "てんかん", "romaji": "tenkan", "english": "Conversion", "thai": "การเปลี่ยนแปลง", "arabic": "تحويل", "russian": "Переключение"},
    {"kanji": "逆転", "kana": "ぎゃくてん", "romaji": "gyakuten", "english": "Reversal", "thai": "การกลับตัว", "arabic": "انعكاส", "russian": "Переворот"},
    {"kanji": "好転", "kana": "こうてん", "romaji": "kouten", "english": "Turn for better", "thai": "การพลิกฟื้น", "arabic": "تحسن", "russian": "Улучшение"},
    {"kanji": "悪転", "kana": "あくてん", "romaji": "akuten", "english": "Turn for worse", "thai": "การพลิกแย่", "arabic": "تدهور", "russian": "Ухудшение"},
    {"kanji": "安泰", "kana": "あんたい", "romaji": "antai", "english": "Security", "thai": "ความปลอดภัย", "arabic": "أمان", "russian": "Безопасность"},
    {"kanji": "危機", "kana": "きき", "romaji": "kiki", "english": "Crisis", "thai": "วิกฤติ", "arabic": "أزمة", "russian": "Кризис"},
    {"kanji": "繁栄", "kana": "はんえい", "romaji": "hanei", "english": "Prosperity", "thai": "ความเจริญรุ่งเรือง", "arabic": "ازدهار", "russian": "Процветание"},
    {"kanji": "衰微", "kana": "すいび", "romaji": "suibi", "english": "Decline", "thai": "ความเสื่อมโทรม", "arabic": "انحطاط", "russian": "Упадок"},
    {"kanji": "隆盛", "kana": "りゅうせい", "romaji": "ryuusei", "english": "Prosperity", "thai": "ความรุ่งเรือง", "arabic": "رخاء", "russian": "Процветание"},
    {"kanji": "衰弱", "kana": "すいじゃく", "romaji": "suijaku", "english": "Weakness", "thai": "ความอ่อนแอ", "arabic": "ضعف", "russian": "Слабость"},
    {"kanji": "健全", "kana": "けんぜん", "romaji": "kenzen", "english": "Soundness", "thai": "ความแข็งแรง", "arabic": "سلامة", "russian": "Здоровье"},
    {"kanji": "病弱", "kana": "びょうじゃく", "romaji": "byoujaku", "english": "Sickness", "thai": "ความเจ็บป่วย", "arabic": "مرض", "russian": "Болезненность"}
]
