# Japanese Vocabulary Database - Part 2 (Words 201-400)

VOCAB_PART2 = [
    # Arts & Literature (201-230)
    {"kanji": "芸術", "kana": "げいじゅつ", "romaji": "geijutsu", "english": "Art", "thai": "ศิลปะ", "arabic": "فن", "russian": "Искусство"},
    {"kanji": "文学", "kana": "ぶんがく", "romaji": "bungaku", "english": "Literature", "thai": "วรรณกรรม", "arabic": "أدب", "russian": "Литература"},
    {"kanji": "詩", "kana": "し", "romaji": "shi", "english": "Poetry", "thai": "บทกวี", "arabic": "شعر", "russian": "Поэзия"},
    {"kanji": "散文", "kana": "さんぶん", "romaji": "sanbun", "english": "Prose", "thai": "ร้อยแก้ว", "arabic": "نثر", "russian": "Проза"},
    {"kanji": "物語", "kana": "ものがたり", "romaji": "monogatari", "english": "Story", "thai": "เรื่องเล่า", "arabic": "قصة", "russian": "Повесть"},
    {"kanji": "小説", "kana": "しょうせつ", "romaji": "shousetsu", "english": "Novel", "thai": "นวนิยาย", "arabic": "رواية", "russian": "Роман"},
    {"kanji": "随筆", "kana": "ずいひつ", "romaji": "zuihitsu", "english": "Essay", "thai": "เรียงความ", "arabic": "مقالة", "russian": "Эссе"},
    {"kanji": "戯曲", "kana": "ぎきょく", "romaji": "gikyoku", "english": "Drama", "thai": "บทละคร", "arabic": "مسرحية", "russian": "Драма"},
    {"kanji": "批評", "kana": "ひひょう", "romaji": "hihyou", "english": "Criticism", "thai": "วิจารณ์", "arabic": "نقد", "russian": "Критика"},
    {"kanji": "表現", "kana": "ひょうげん", "romaji": "hyougen", "english": "Expression", "thai": "การแสดงออก", "arabic": "تعبير", "russian": "Выражение"},
    {"kanji": "描写", "kana": "びょうしゃ", "romaji": "byousha", "english": "Description", "thai": "การบรรยาย", "arabic": "وصف", "russian": "Описание"},
    {"kanji": "比喩", "kana": "ひゆ", "romaji": "hiyu", "english": "Metaphor", "thai": "อุปมา", "arabic": "استعارة", "russian": "Метафора"},
    {"kanji": "象徴", "kana": "しょうちょう", "romaji": "shouchou", "english": "Symbol", "thai": "สัญลักษณ์", "arabic": "رمز", "russian": "Символ"},
    {"kanji": "主題", "kana": "しゅだい", "romaji": "shudai", "english": "Theme", "thai": "ธีม", "arabic": "موضوع", "russian": "Тема"},
    {"kanji": "構成", "kana": "こうせい", "romaji": "kousei", "english": "Composition", "thai": "โครงสร้าง", "arabic": "تكوين", "russian": "Композиция"},
    {"kanji": "韻律", "kana": "いんりつ", "romaji": "inritsu", "english": "Rhythm", "thai": "จังหวะ", "arabic": "إيقاع", "russian": "Ритм"},
    {"kanji": "韻", "kana": "いん", "romaji": "in", "english": "Rhyme", "thai": "สัมผัส", "arabic": "قافية", "russian": "Рифма"},
    {"kanji": "旋律", "kana": "せんりつ", "romaji": "senritsu", "english": "Melody", "thai": "ทำนอง", "arabic": "لحن", "russian": "Мелодия"},
    {"kanji": "和音", "kana": "わおん", "romaji": "waon", "english": "Harmony", "thai": "ฮาร์โมนี", "arabic": "تناغم", "russian": "Гармония"},
    {"kanji": "音階", "kana": "おんかい", "romaji": "onkai", "english": "Scale", "thai": "บันไดเสียง", "arabic": "سلم موسيقي", "russian": "Гамма"},
    {"kanji": "楽譜", "kana": "がくふ", "romaji": "gakufu", "english": "Score", "thai": "โน้ตเพลง", "arabic": "نوتة موسيقية", "russian": "Ноты"},
    {"kanji": "演奏", "kana": "えんそう", "romaji": "ensou", "english": "Performance", "thai": "การแสดง", "arabic": "أداء", "russian": "Исполнение"},
    {"kanji": "指揮", "kana": "しき", "romaji": "shiki", "english": "Conducting", "thai": "การควบคุม", "arabic": "قيادة", "russian": "Дирижирование"},
    {"kanji": "作曲", "kana": "さっきょく", "romaji": "sakkyoku", "english": "Composition", "thai": "การแต่งเพลง", "arabic": "تأليف", "russian": "Композиция"},
    {"kanji": "編曲", "kana": "へんきょく", "romaji": "henkyoku", "english": "Arrangement", "thai": "การเรียบเรียง", "arabic": "توزيع", "russian": "Аранжировка"},
    {"kanji": "絵画", "kana": "かいが", "romaji": "kaiga", "english": "Painting", "thai": "จิตรกรรม", "arabic": "رسم", "russian": "Живопись"},
    {"kanji": "彫刻", "kana": "ちょうこく", "romaji": "choukoku", "english": "Sculpture", "thai": "ประติมากรรม", "arabic": "نحت", "russian": "Скульптура"},
    {"kanji": "建築", "kana": "けんちく", "romaji": "kenchiku", "english": "Architecture", "thai": "สถาปัตยกรรม", "arabic": "عمارة", "russian": "Архитектура"},
    {"kanji": "陶芸", "kana": "とうげい", "romaji": "tougei", "english": "Pottery", "thai": "เครื่องปั้นดินเผา", "arabic": "فخار", "russian": "Гончарство"},
    {"kanji": "工芸", "kana": "こうげい", "romaji": "kougei", "english": "Craft", "thai": "หัตถกรรม", "arabic": "حرفة", "russian": "Ремесло"},

    # Law & Justice (231-260)
    {"kanji": "法律", "kana": "ほうりつ", "romaji": "houritsu", "english": "Law", "thai": "กฎหมาย", "arabic": "قانون", "russian": "Закон"},
    {"kanji": "裁判", "kana": "さいばん", "romaji": "saiban", "english": "Trial", "thai": "การพิจารณาคดี", "arabic": "محاكمة", "russian": "Суд"},
    {"kanji": "判決", "kana": "はんけつ", "romaji": "hanketsu", "english": "Verdict", "thai": "คำตัดสิน", "arabic": "حكم", "russian": "Приговор"},
    {"kanji": "刑罰", "kana": "けいばつ", "romaji": "keibatsu", "english": "Punishment", "thai": "การลงโทษ", "arabic": "عقوبة", "russian": "Наказание"},
    {"kanji": "罪", "kana": "つみ", "romaji": "tsumi", "english": "Crime", "thai": "อาชญากรรม", "arabic": "جريمة", "russian": "Преступление"},
    {"kanji": "無罪", "kana": "むざい", "romaji": "muzai", "english": "Innocence", "thai": "ความบริสุทธิ์", "arabic": "براءة", "russian": "Невиновность"},
    {"kanji": "有罪", "kana": "ゆうざい", "romaji": "yuuzai", "english": "Guilt", "thai": "ความผิด", "arabic": "إدانة", "russian": "Виновность"},
    {"kanji": "証拠", "kana": "しょうこ", "romaji": "shouko", "english": "Evidence", "thai": "หลักฐาน", "arabic": "دليل", "russian": "Доказательство"},
    {"kanji": "証言", "kana": "しょうげん", "romaji": "shougen", "english": "Testimony", "thai": "คำเบิกความ", "arabic": "شهادة", "russian": "Показание"},
    {"kanji": "弁護", "kana": "べんご", "romaji": "bengo", "english": "Defense", "thai": "การป้องกัน", "arabic": "دفاع", "russian": "Защита"},
    {"kanji": "告訴", "kana": "こくそ", "romaji": "kokuso", "english": "Accusation", "thai": "การกล่าวหา", "arabic": "اتهام", "russian": "Обвинение"},
    {"kanji": "訴訟", "kana": "そしょう", "romaji": "soshou", "english": "Lawsuit", "thai": "คดีความ", "arabic": "دعوى", "russian": "Иск"},
    {"kanji": "被告", "kana": "ひこく", "romaji": "hikoku", "english": "Defendant", "thai": "จำเลย", "arabic": "متهم", "russian": "Обвиняемый"},
    {"kanji": "原告", "kana": "げんこく", "romaji": "genkoku", "english": "Plaintiff", "thai": "โจทก์", "arabic": "مدعي", "russian": "Истец"},
    {"kanji": "検察", "kana": "けんさつ", "romaji": "kensatsu", "english": "Prosecution", "thai": "อัยการ", "arabic": "نيابة", "russian": "Прокуратура"},
    {"kanji": "弁護士", "kana": "べんごし", "romaji": "bengoshi", "english": "Lawyer", "thai": "ทนายความ", "arabic": "محامي", "russian": "Адвокат"},
    {"kanji": "裁判官", "kana": "さいばんかん", "romaji": "saibankan", "english": "Judge", "thai": "ผู้พิพากษา", "arabic": "قاضي", "russian": "Судья"},
    {"kanji": "陪審", "kana": "ばいしん", "romaji": "baishin", "english": "Jury", "thai": "คณะลูกขุน", "arabic": "هيئة محلفين", "russian": "Жюри присяжных"},
    {"kanji": "憲法", "kana": "けんぽう", "romaji": "kenpou", "english": "Constitution", "thai": "รัฐธรรมนูญ", "arabic": "دستور", "russian": "Конституция"},
    {"kanji": "条例", "kana": "じょうれい", "romaji": "jourei", "english": "Ordinance", "thai": "เทศบัญญัติ", "arabic": "لائحة", "russian": "Постановление"},
    {"kanji": "違反", "kana": "いはん", "romaji": "ihan", "english": "Violation", "thai": "การละเมิด", "arabic": "مخالفة", "russian": "Нарушение"},
    {"kanji": "遵守", "kana": "じゅんしゅ", "romaji": "junshu", "english": "Compliance", "thai": "การปฏิบัติตาม", "arabic": "امتثال", "russian": "Соблюдение"},
    {"kanji": "禁止", "kana": "きんし", "romaji": "kinshi", "english": "Prohibition", "thai": "การห้าม", "arabic": "حظر", "russian": "Запрет"},
    {"kanji": "許可", "kana": "きょか", "romaji": "kyoka", "english": "Permission", "thai": "การอนุญาต", "arabic": "إذن", "russian": "Разрешение"},
    {"kanji": "免許", "kana": "めんきょ", "romaji": "menkyo", "english": "License", "thai": "ใบอนุญาต", "arabic": "رخصة", "russian": "Лицензия"},
    {"kanji": "賠償", "kana": "ばいしょう", "romaji": "baishou", "english": "Compensation", "thai": "การชดใช้", "arabic": "تعويض", "russian": "Компенсация"},
    {"kanji": "賠償金", "kana": "ばいしょうきん", "romaji": "baishoukin", "english": "Damages", "thai": "ค่าเสียหาย", "arabic": "تعويضات", "russian": "Возмещение"},
    {"kanji": "保釈", "kana": "ほしゃく", "romaji": "hoshaku", "english": "Bail", "thai": "การประกันตัว", "arabic": "كفالة", "russian": "Залог"},
    {"kanji": "拘留", "kana": "こうりゅう", "romaji": "kouryuu", "english": "Detention", "thai": "การกักขัง", "arabic": "احتجاز", "russian": "Задержание"},
    {"kanji": "釈放", "kana": "しゃくほう", "romaji": "shakuhou", "english": "Release", "thai": "การปล่อยตัว", "arabic": "إطلاق سراح", "russian": "Освобождение"},

    # Medicine & Health (261-290)
    {"kanji": "医療", "kana": "いりょう", "romaji": "iryou", "english": "Medical care", "thai": "การแพทย์", "arabic": "رعاية طبية", "russian": "Медицина"},
    {"kanji": "診断", "kana": "しんだん", "romaji": "shindan", "english": "Diagnosis", "thai": "การวินิจฉัย", "arabic": "تشخيص", "russian": "Диагностика"},
    {"kanji": "治療", "kana": "ちりょう", "romaji": "chiryou", "english": "Treatment", "thai": "การรักษา", "arabic": "علاج", "russian": "Лечение"},
    {"kanji": "手術", "kana": "しゅじゅつ", "romaji": "shujutsu", "english": "Surgery", "thai": "การผ่าตัด", "arabic": "جراحة", "russian": "Операция"},
    {"kanji": "処方", "kana": "しょほう", "romaji": "shohou", "english": "Prescription", "thai": "ใบสั่งยา", "arabic": "وصفة", "russian": "Рецепт"},
    {"kanji": "投薬", "kana": "とうやく", "romaji": "touyaku", "english": "Medication", "thai": "การให้ยา", "arabic": "دواء", "russian": "Медикаменты"},
    {"kanji": "症状", "kana": "しょうじょう", "romaji": "shoujou", "english": "Symptom", "thai": "อาการ", "arabic": "عرض", "russian": "Симптом"},
    {"kanji": "疾患", "kana": "しっかん", "romaji": "shikkan", "english": "Disease", "thai": "โรค", "arabic": "مرض", "russian": "Болезнь"},
    {"kanji": "感染", "kana": "かんせん", "romaji": "kansen", "english": "Infection", "thai": "การติดเชื้อ", "arabic": "عدوى", "russian": "Инфекция"},
    {"kanji": "免疫", "kana": "めんえき", "romaji": "meneki", "english": "Immunity", "thai": "ภูมิคุ้มกัน", "arabic": "مناعة", "russian": "Иммунитет"},
    {"kanji": "予防", "kana": "よぼう", "romaji": "yobou", "english": "Prevention", "thai": "การป้องกัน", "arabic": "وقاية", "russian": "Профилактика"},
    {"kanji": "接種", "kana": "せっしゅ", "romaji": "sesshu", "english": "Vaccination", "thai": "การฉีดวัคซีน", "arabic": "تطعيم", "russian": "Вакцинация"},
    {"kanji": "抗体", "kana": "こうたい", "romaji": "koutai", "english": "Antibody", "thai": "แอนติบอดี", "arabic": "جسم مضاد", "russian": "Антитело"},
    {"kanji": "病原体", "kana": "びょうげんたい", "romaji": "byougentai", "english": "Pathogen", "thai": "เชื้อโรค", "arabic": "مسبب المرض", "russian": "Патоген"},
    {"kanji": "細菌", "kana": "さいきん", "romaji": "saikin", "english": "Bacteria", "thai": "แบคทีเรีย", "arabic": "بكتيريا", "russian": "Бактерия"},
    {"kanji": "病毒", "kana": "ウイルス", "romaji": "uirusu", "english": "Virus", "thai": "ไวรัส", "arabic": "فيروس", "russian": "Вирус"},
    {"kanji": "炎症", "kana": "えんしょう", "romaji": "enshou", "english": "Inflammation", "thai": "การอักเสบ", "arabic": "التهاب", "russian": "Воспаление"},
    {"kanji": "腫瘍", "kana": "しゅよう", "romaji": "shuyou", "english": "Tumor", "thai": "เนื้องอก", "arabic": "ورم", "russian": "Опухоль"},
    {"kanji": "癌", "kana": "がん", "romaji": "gan", "english": "Cancer", "thai": "มะเร็ง", "arabic": "سرطان", "russian": "Рак"},
    {"kanji": "良性", "kana": "りょうせい", "romaji": "ryousei", "english": "Benign", "thai": "ไม่ร้ายแรง", "arabic": "حميد", "russian": "Доброкачественный"},
    {"kanji": "悪性", "kana": "あくせい", "romaji": "akusei", "english": "Malignant", "thai": "ร้ายแรง", "arabic": "خبيث", "russian": "Злокачественный"},
    {"kanji": "転移", "kana": "てんい", "romaji": "ten'i", "english": "Metastasis", "thai": "การแพร่กระจาย", "arabic": "انتقال", "russian": "Метастаз"},
    {"kanji": "寛解", "kana": "かんかい", "romaji": "kankai", "english": "Remission", "thai": "การบรรเทา", "arabic": "هدأة", "russian": "Ремиссия"},
    {"kanji": "再発", "kana": "さいはつ", "romaji": "saihatsu", "english": "Relapse", "thai": "การกลับเป็นซ้ำ", "arabic": "انتكاسة", "russian": "Рецидив"},
    {"kanji": "合併症", "kana": "がっぺいしょう", "romaji": "gappeishou", "english": "Complication", "thai": "ภาวะแทรกซ้อน", "arabic": "مضاعفات", "russian": "Осложнение"},
    {"kanji": "後遺症", "kana": "こういしょう", "romaji": "kouishou", "english": "Sequela", "thai": "ผลข้างเคียง", "arabic": "أثر جانبي", "russian": "Последствие"},
    {"kanji": "麻酔", "kana": "ますい", "romaji": "masui", "english": "Anesthesia", "thai": "การดมยาสลบ", "arabic": "تخدير", "russian": "Анестезия"},
    {"kanji": "輸血", "kana": "ゆけつ", "romaji": "yuketsu", "english": "Transfusion", "thai": "การถ่ายเลือด", "arabic": "نقل دم", "russian": "Переливание"},
    {"kanji": "移植", "kana": "いしょく", "romaji": "ishoku", "english": "Transplant", "thai": "การปลูกถ่าย", "arabic": "زراعة", "russian": "Трансплантация"},
    {"kanji": "臓器", "kana": "ぞうき", "romaji": "zouki", "english": "Organ", "thai": "อวัยวะ", "arabic": "عضو", "russian": "Орган"},

    # Education & Learning (291-320)
    {"kanji": "教育", "kana": "きょういく", "romaji": "kyouiku", "english": "Education", "thai": "การศึกษา", "arabic": "تعليم", "russian": "Образование"},
    {"kanji": "学習", "kana": "がくしゅう", "romaji": "gakushuu", "english": "Learning", "thai": "การเรียนรู้", "arabic": "تعلم", "russian": "Обучение"},
    {"kanji": "指導", "kana": "しどう", "romaji": "shidou", "english": "Guidance", "thai": "การแนะนำ", "arabic": "إرشاد", "russian": "Руководство"},
    {"kanji": "訓練", "kana": "くんれん", "romaji": "kunren", "english": "Training", "thai": "การฝึกอบรม", "arabic": "تدريب", "russian": "Тренировка"},
    {"kanji": "修得", "kana": "しゅうとく", "romaji": "shuutoku", "english": "Acquisition", "thai": "การได้มา", "arabic": "اكتساب", "russian": "Приобретение"},
    {"kanji": "習得", "kana": "しゅうとく", "romaji": "shuutoku", "english": "Mastery", "thai": "การเชี่ยวชาญ", "arabic": "إتقان", "russian": "Овладение"},
    {"kanji": "理解", "kana": "りかい", "romaji": "rikai", "english": "Understanding", "thai": "ความเข้าใจ", "arabic": "فهم", "russian": "Понимание"},
    {"kanji": "把握", "kana": "はあく", "romaji": "haaku", "english": "Grasp", "thai": "การจับใจความ", "arabic": "إدراك", "russian": "Понимание"},
    {"kanji": "暗記", "kana": "あんき", "romaji": "anki", "english": "Memorization", "thai": "การท่องจำ", "arabic": "حفظ", "russian": "Запоминание"},
    {"kanji": "復習", "kana": "ふくしゅう", "romaji": "fukushuu", "english": "Review", "thai": "การทบทวน", "arabic": "مراجعة", "russian": "Повторение"},
    {"kanji": "予習", "kana": "よしゅう", "romaji": "yoshuu", "english": "Preview", "thai": "การเตรียมบทเรียน", "arabic": "تحضير", "russian": "Предварительное изучение"},
    {"kanji": "試験", "kana": "しけん", "romaji": "shiken", "english": "Examination", "thai": "การสอบ", "arabic": "امتحان", "russian": "Экзамен"},
    {"kanji": "評価", "kana": "ひょうか", "romaji": "hyouka", "english": "Evaluation", "thai": "การประเมิน", "arabic": "تقييم", "russian": "Оценка"},
    {"kanji": "成績", "kana": "せいせき", "romaji": "seiseki", "english": "Grade", "thai": "เกรด", "arabic": "درجة", "russian": "Оценка"},
    {"kanji": "合格", "kana": "ごうかく", "romaji": "goukaku", "english": "Pass", "thai": "ผ่าน", "arabic": "نجاح", "russian": "Сдача"},
    {"kanji": "不合格", "kana": "ふごうかく", "romaji": "fugoukaku", "english": "Fail", "thai": "ไม่ผ่าน", "arabic": "رسوب", "russian": "Провал"},
    {"kanji": "卒業", "kana": "そつぎょう", "romaji": "sotsugyou", "english": "Graduation", "thai": "การจบการศึกษา", "arabic": "تخرج", "russian": "Выпуск"},
    {"kanji": "入学", "kana": "にゅうがく", "romaji": "nyuugaku", "english": "Enrollment", "thai": "การเข้าเรียน", "arabic": "التحاق", "russian": "Поступление"},
    {"kanji": "進学", "kana": "しんがく", "romaji": "shingaku", "english": "Advancement", "thai": "การศึกษาต่อ", "arabic": "متابعة الدراسة", "russian": "Продолжение учёбы"},
    {"kanji": "退学", "kana": "たいがく", "romaji": "taigaku", "english": "Dropout", "thai": "การลาออก", "arabic": "ترك الدراسة", "russian": "Отчисление"},
    {"kanji": "奨学金", "kana": "しょうがくきん", "romaji": "shougakukin", "english": "Scholarship", "thai": "ทุนการศึกษา", "arabic": "منحة دراسية", "russian": "Стипендия"},
    {"kanji": "授業", "kana": "じゅぎょう", "romaji": "jugyou", "english": "Lesson", "thai": "บทเรียน", "arabic": "درس", "russian": "Урок"},
    {"kanji": "講義", "kana": "こうぎ", "romaji": "kougi", "english": "Lecture", "thai": "การบรรยาย", "arabic": "محاضرة", "russian": "Лекция"},
    {"kanji": "演習", "kana": "えんしゅう", "romaji": "enshuu", "english": "Seminar", "thai": "การฝึกปฏิบัติ", "arabic": "تمرين", "russian": "Семинар"},
    {"kanji": "実習", "kana": "じっしゅう", "romaji": "jisshuu", "english": "Practicum", "thai": "การฝึกงาน", "arabic": "تطبيق عملي", "russian": "Практика"},
    {"kanji": "課題", "kana": "かだい", "romaji": "kadai", "english": "Assignment", "thai": "การบ้าน", "arabic": "واجب", "russian": "Задание"},
    {"kanji": "論文", "kana": "ろんぶん", "romaji": "ronbun", "english": "Thesis", "thai": "วิทยานิพนธ์", "arabic": "أطروحة", "russian": "Диссертация"},
    {"kanji": "発表", "kana": "はっぴょう", "romaji": "happyou", "english": "Presentation", "thai": "การนำเสนอ", "arabic": "عرض", "russian": "Презентация"},
    {"kanji": "討論", "kana": "とうろん", "romaji": "touron", "english": "Discussion", "thai": "การอภิปราย", "arabic": "مناقشة", "russian": "Дискуссия"},
    {"kanji": "質問", "kana": "しつもん", "romaji": "shitsumon", "english": "Question", "thai": "คำถาม", "arabic": "سؤال", "russian": "Вопрос"},

    # Time & Change (321-350)
    {"kanji": "瞬間", "kana": "しゅんかん", "romaji": "shunkan", "english": "Moment", "thai": "ช่วงเวลา", "arabic": "لحظة", "russian": "Момент"},
    {"kanji": "期間", "kana": "きかん", "romaji": "kikan", "english": "Period", "thai": "ระยะเวลา", "arabic": "فترة", "russian": "Период"},
    {"kanji": "永遠", "kana": "えいえん", "romaji": "eien", "english": "Eternity", "thai": "นิรันดร", "arabic": "أبدية", "russian": "Вечность"},
    {"kanji": "一時", "kana": "いちじ", "romaji": "ichiji", "english": "Temporary", "thai": "ชั่วคราว", "arabic": "مؤقت", "russian": "Временный"},
    {"kanji": "恒久", "kana": "こうきゅう", "romaji": "koukyuu", "english": "Permanent", "thai": "ถาวร", "arabic": "دائم", "russian": "Постоянный"},
    {"kanji": "変化", "kana": "へんか", "romaji": "henka", "english": "Change", "thai": "การเปลี่ยนแปลง", "arabic": "تغيير", "russian": "Изменение"},
    {"kanji": "変動", "kana": "へんどう", "romaji": "hendou", "english": "Fluctuation", "thai": "การผันผวน", "arabic": "تقلب", "russian": "Колебание"},
    {"kanji": "変遷", "kana": "へんせん", "romaji": "hensen", "english": "Transition", "thai": "การเปลี่ยนผ่าน", "arabic": "انتقال", "russian": "Переход"},
    {"kanji": "進化", "kana": "しんか", "romaji": "shinka", "english": "Evolution", "thai": "วิวัฒนาการ", "arabic": "تطور", "russian": "Эволюция"},
    {"kanji": "退化", "kana": "たいか", "romaji": "taika", "english": "Degeneration", "thai": "การเสื่อม", "arabic": "تدهور", "russian": "Деградация"},
    {"kanji": "成長", "kana": "せいちょう", "romaji": "seichou", "english": "Growth", "thai": "การเติบโต", "arabic": "نمو", "russian": "Рост"},
    {"kanji": "発展", "kana": "はってん", "romaji": "hatten", "english": "Development", "thai": "การพัฒนา", "arabic": "تطور", "russian": "Развитие"},
    {"kanji": "衰退", "kana": "すいたい", "romaji": "suitai", "english": "Decline", "thai": "การเสื่อมถอย", "arabic": "تراجع", "russian": "Упадок"},
    {"kanji": "崩壊", "kana": "ほうかい", "romaji": "houkai", "english": "Collapse", "thai": "การล่มสลาย", "arabic": "انهيار", "russian": "Крах"},
    {"kanji": "再建", "kana": "さいけん", "romaji": "saiken", "english": "Reconstruction", "thai": "การสร้างใหม่", "arabic": "إعادة بناء", "russian": "Восстановление"},
    {"kanji": "創造", "kana": "そうぞう", "romaji": "souzou", "english": "Creation", "thai": "การสร้างสรรค์", "arabic": "خلق", "russian": "Создание"},
    {"kanji": "破滅", "kana": "はめつ", "romaji": "hametsu", "english": "Destruction", "thai": "การทำลายล้าง", "arabic": "دمار", "russian": "Разрушение"},
    {"kanji": "起源", "kana": "きげん", "romaji": "kigen", "english": "Origin", "thai": "ต้นกำเนิด", "arabic": "أصل", "russian": "Происхождение"},
    {"kanji": "終焉", "kana": "しゅうえん", "romaji": "shuuen", "english": "End", "thai": "จุดสิ้นสุด", "arabic": "نهاية", "russian": "Конец"},
    {"kanji": "継続", "kana": "けいぞく", "romaji": "keizoku", "english": "Continuation", "thai": "การดำเนินต่อ", "arabic": "استمرار", "russian": "Продолжение"},
    {"kanji": "中断", "kana": "ちゅうだん", "romaji": "chuudan", "english": "Interruption", "thai": "การหยุดชะงัก", "arabic": "انقطاع", "russian": "Прерывание"},
    {"kanji": "停止", "kana": "ていし", "romaji": "teishi", "english": "Stop", "thai": "การหยุด", "arabic": "توقف", "russian": "Остановка"},
    {"kanji": "開始", "kana": "かいし", "romaji": "kaishi", "english": "Start", "thai": "การเริ่มต้น", "arabic": "بداية", "russian": "Начало"},
    {"kanji": "完了", "kana": "かんりょう", "romaji": "kanryou", "english": "Completion", "thai": "การสำเร็จ", "arabic": "إتمام", "russian": "Завершение"},
    {"kanji": "未完", "kana": "みかん", "romaji": "mikan", "english": "Incomplete", "thai": "ไม่สมบูรณ์", "arabic": "غير مكتمل", "russian": "Незавершённый"},
    {"kanji": "加速", "kana": "かそく", "romaji": "kasoku", "english": "Acceleration", "thai": "การเร่ง", "arabic": "تسارع", "russian": "Ускорение"},
    {"kanji": "減速", "kana": "げんそく", "romaji": "gensoku", "english": "Deceleration", "thai": "การชะลอ", "arabic": "تباطؤ", "russian": "Замедление"},
    {"kanji": "停滞", "kana": "ていたい", "romaji": "teitai", "english": "Stagnation", "thai": "ความซบเซา", "arabic": "ركود", "russian": "Застой"},
    {"kanji": "活性", "kana": "かっせい", "romaji": "kassei", "english": "Activation", "thai": "การกระตุ้น", "arabic": "تنشيط", "russian": "Активация"},
    {"kanji": "沈黙", "kana": "ちんもく", "romaji": "chinmoku", "english": "Silence", "thai": "ความเงียบ", "arabic": "صمت", "russian": "Молчание"},

    # Space & Distance (351-380)
    {"kanji": "空間", "kana": "くうかん", "romaji": "kuukan", "english": "Space", "thai": "พื้นที่", "arabic": "فضاء", "russian": "Пространство"},
    {"kanji": "距離", "kana": "きょり", "romaji": "kyori", "english": "Distance", "thai": "ระยะทาง", "arabic": "مسافة", "russian": "Расстояние"},
    {"kanji": "領域", "kana": "りょういき", "romaji": "ryouiki", "english": "Domain", "thai": "ขอบเขต", "arabic": "مجال", "russian": "Область"},
    {"kanji": "範囲", "kana": "はんい", "romaji": "han'i", "english": "Range", "thai": "ช่วง", "arabic": "نطاق", "russian": "Диапазон"},
    {"kanji": "境界", "kana": "きょうかい", "romaji": "kyoukai", "english": "Boundary", "thai": "เขตแดน", "arabic": "حدود", "russian": "Граница"},
    {"kanji": "限界", "kana": "げんかい", "romaji": "genkai", "english": "Limit", "thai": "ขีดจำกัด", "arabic": "حد", "russian": "Предел"},
    {"kanji": "無限", "kana": "むげん", "romaji": "mugen", "english": "Infinite", "thai": "ไม่จำกัด", "arabic": "لا نهائي", "russian": "Бесконечный"},
    {"kanji": "有限", "kana": "ゆうげん", "romaji": "yuugen", "english": "Finite", "thai": "จำกัด", "arabic": "محدود", "russian": "Конечный"},
    {"kanji": "中心", "kana": "ちゅうしん", "romaji": "chuushin", "english": "Center", "thai": "ศูนย์กลาง", "arabic": "مركز", "russian": "Центр"},
    {"kanji": "周辺", "kana": "しゅうへん", "romaji": "shuuhen", "english": "Periphery", "thai": "รอบนอก", "arabic": "محيط", "russian": "Периферия"},
    {"kanji": "内部", "kana": "ないぶ", "romaji": "naibu", "english": "Interior", "thai": "ภายใน", "arabic": "داخل", "russian": "Внутренность"},
    {"kanji": "外部", "kana": "がいぶ", "romaji": "gaibu", "english": "Exterior", "thai": "ภายนอก", "arabic": "خارج", "russian": "Внешность"},
    {"kanji": "表面", "kana": "ひょうめん", "romaji": "hyoumen", "english": "Surface", "thai": "พื้นผิว", "arabic": "سطح", "russian": "Поверхность"},
    {"kanji": "深層", "kana": "しんそう", "romaji": "shinsou", "english": "Deep layer", "thai": "ชั้นลึก", "arabic": "طبقة عميقة", "russian": "Глубинный слой"},
    {"kanji": "上層", "kana": "じょうそう", "romaji": "jousou", "english": "Upper layer", "thai": "ชั้นบน", "arabic": "طبقة علوية", "russian": "Верхний слой"},
    {"kanji": "下層", "kana": "かそう", "romaji": "kasou", "english": "Lower layer", "thai": "ชั้นล่าง", "arabic": "طبقة سفلية", "russian": "Нижний слой"},
    {"kanji": "頂点", "kana": "ちょうてん", "romaji": "chouten", "english": "Peak", "thai": "จุดสูงสุด", "arabic": "قمة", "russian": "Вершина"},
    {"kanji": "底辺", "kana": "ていへん", "romaji": "teihen", "english": "Bottom", "thai": "ฐาน", "arabic": "قاعدة", "russian": "Основание"},
    {"kanji": "平面", "kana": "へいめん", "romaji": "heimen", "english": "Plane", "thai": "ระนาบ", "arabic": "مستوى", "russian": "Плоскость"},
    {"kanji": "立体", "kana": "りったい", "romaji": "rittai", "english": "Solid", "thai": "ทรงตัน", "arabic": "مجسم", "russian": "Твёрдое тело"},
    {"kanji": "密度", "kana": "みつど", "romaji": "mitsudo", "english": "Density", "thai": "ความหนาแน่น", "arabic": "كثافة", "russian": "Плотность"},
    {"kanji": "濃度", "kana": "のうど", "romaji": "noudo", "english": "Concentration", "thai": "ความเข้มข้น", "arabic": "تركيز", "russian": "Концентрация"},
    {"kanji": "容積", "kana": "ようせき", "romaji": "youseki", "english": "Volume", "thai": "ปริมาตร", "arabic": "حجم", "russian": "Объём"},
    {"kanji": "面積", "kana": "めんせき", "romaji": "menseki", "english": "Area", "thai": "พื้นที่", "arabic": "مساحة", "russian": "Площадь"},
    {"kanji": "長さ", "kana": "ながさ", "romaji": "nagasa", "english": "Length", "thai": "ความยาว", "arabic": "طول", "russian": "Длина"},
    {"kanji": "幅", "kana": "はば", "romaji": "haba", "english": "Width", "thai": "ความกว้าง", "arabic": "عرض", "russian": "Ширина"},
    {"kanji": "高さ", "kana": "たかさ", "romaji": "takasa", "english": "Height", "thai": "ความสูง", "arabic": "ارتفاع", "russian": "Высота"},
    {"kanji": "深さ", "kana": "ふかさ", "romaji": "fukasa", "english": "Depth", "thai": "ความลึก", "arabic": "عمق", "russian": "Глубина"},
    {"kanji": "厚さ", "kana": "あつさ", "romaji": "atsusa", "english": "Thickness", "thai": "ความหนา", "arabic": "سماكة", "russian": "Толщина"},
    {"kanji": "重さ", "kana": "おもさ", "romaji": "omosa", "english": "Weight", "thai": "น้ำหนัก", "arabic": "وزن", "russian": "Вес"},

    # Quality & Quantity (381-400)
    {"kanji": "品質", "kana": "ひんしつ", "romaji": "hinshitsu", "english": "Quality", "thai": "คุณภาพ", "arabic": "جودة", "russian": "Качество"},
    {"kanji": "数量", "kana": "すうりょう", "romaji": "suuryou", "english": "Quantity", "thai": "ปริมาณ", "arabic": "كمية", "russian": "Количество"},
    {"kanji": "程度", "kana": "ていど", "romaji": "teido", "english": "Degree", "thai": "ระดับ", "arabic": "درجة", "russian": "Степень"},
    {"kanji": "水準", "kana": "すいじゅん", "romaji": "suijun", "english": "Level", "thai": "ระดับ", "arabic": "مستوى", "russian": "Уровень"},
    {"kanji": "標準", "kana": "ひょうじゅん", "romaji": "hyoujun", "english": "Standard", "thai": "มาตรฐาน", "arabic": "معيار", "russian": "Стандарт"},
    {"kanji": "平均", "kana": "へいきん", "romaji": "heikin", "english": "Average", "thai": "ค่าเฉลี่ย", "arabic": "متوسط", "russian": "Среднее"},
    {"kanji": "最大", "kana": "さいだい", "romaji": "saidai", "english": "Maximum", "thai": "สูงสุด", "arabic": "أقصى", "russian": "Максимум"},
    {"kanji": "最小", "kana": "さいしょう", "romaji": "saishou", "english": "Minimum", "thai": "ต่ำสุด", "arabic": "أدنى", "russian": "Минимум"},
    {"kanji": "増加", "kana": "ぞうか", "romaji": "zouka", "english": "Increase", "thai": "การเพิ่ม", "arabic": "زيادة", "russian": "Увеличение"},
    {"kanji": "減少", "kana": "げんしょう", "romaji": "genshou", "english": "Decrease", "thai": "การลด", "arabic": "نقص", "russian": "Уменьшение"},
    {"kanji": "過剰", "kana": "かじょう", "romaji": "kajou", "english": "Excess", "thai": "ส่วนเกิน", "arabic": "فائض", "russian": "Избыток"},
    {"kanji": "不足", "kana": "ふそく", "romaji": "fusoku", "english": "Shortage", "thai": "ขาดแคลน", "arabic": "نقص", "russian": "Нехватка"},
    {"kanji": "充足", "kana": "じゅうそく", "romaji": "juusoku", "english": "Sufficiency", "thai": "เพียงพอ", "arabic": "كفاية", "russian": "Достаточность"},
    {"kanji": "豊富", "kana": "ほうふ", "romaji": "houfu", "english": "Abundance", "thai": "ความอุดมสมบูรณ์", "arabic": "وفرة", "russian": "Изобилие"},
    {"kanji": "希少", "kana": "きしょう", "romaji": "kishou", "english": "Scarcity", "thai": "ความหายาก", "arabic": "ندرة", "russian": "Редкость"},
    {"kanji": "優良", "kana": "ゆうりょう", "romaji": "yuuryou", "english": "Excellent", "thai": "ยอดเยี่ยม", "arabic": "ممتاز", "russian": "Отличный"},
    {"kanji": "劣悪", "kana": "れつあく", "romaji": "retsuaku", "english": "Inferior", "thai": "ด้อยคุณภาพ", "arabic": "رديء", "russian": "Низкокачественный"},
    {"kanji": "完璧", "kana": "かんぺき", "romaji": "kanpeki", "english": "Perfect", "thai": "สมบูรณ์แบบ", "arabic": "مثالي", "russian": "Совершенный"},
    {"kanji": "欠陥", "kana": "けっかん", "romaji": "kekkan", "english": "Defect", "thai": "ข้อบกพร่อง", "arabic": "عيب", "russian": "Дефект"},
    {"kanji": "均一", "kana": "きんいつ", "romaji": "kin'itsu", "english": "Uniform", "thai": "เหมือนกัน", "arabic": "موحد", "russian": "Единообразный"}
]
