# Japanese Vocabulary Database - Part 4 (Words 601-800)

VOCAB_PART4 = [
    # Emotions & Feelings (601-650)
    {"kanji": "感動", "kana": "かんどう", "romaji": "kandou", "english": "Emotion", "thai": "ความประทับใจ", "arabic": "تأثر", "russian": "Волнение"},
    {"kanji": "興奮", "kana": "こうふん", "romaji": "koufun", "english": "Excitement", "thai": "ความตื่นเต้น", "arabic": "إثارة", "russian": "Возбуждение"},
    {"kanji": "平静", "kana": "へいせい", "romaji": "heisei", "english": "Calm", "thai": "ความสงบ", "arabic": "هدوء", "russian": "Спокойствие"},
    {"kanji": "動揺", "kana": "どうよう", "romaji": "douyou", "english": "Agitation", "thai": "ความวุ่นวาย", "arabic": "قلق", "russian": "Волнение"},
    {"kanji": "落ち着き", "kana": "おちつき", "romaji": "ochitsuki", "english": "Composure", "thai": "ความสงบเยือกเย็น", "arabic": "هدوء", "russian": "Хладнокровие"},
    {"kanji": "焦燥", "kana": "しょうそう", "romaji": "shousou", "english": "Impatience", "thai": "ความใจร้อน", "arabic": "قلق", "russian": "Нетерпение"},
    {"kanji": "安心", "kana": "あんしん", "romaji": "anshin", "english": "Relief", "thai": "ความอุ่นใจ", "arabic": "طمأنينة", "russian": "Облегчение"},
    {"kanji": "心配", "kana": "しんぱい", "romaji": "shinpai", "english": "Worry", "thai": "ความกังวล", "arabic": "قلق", "russian": "Беспокойство"},
    {"kanji": "満足", "kana": "まんぞく", "romaji": "manzoku", "english": "Satisfaction", "thai": "ความพอใจ", "arabic": "رضا", "russian": "Удовлетворение"},
    {"kanji": "不満", "kana": "ふまん", "romaji": "fuman", "english": "Dissatisfaction", "thai": "ความไม่พอใจ", "arabic": "عدم رضا", "russian": "Недовольство"},
    {"kanji": "幸福", "kana": "こうふく", "romaji": "koufuku", "english": "Happiness", "thai": "ความสุข", "arabic": "سعادة", "russian": "Счастье"},
    {"kanji": "不幸", "kana": "ふこう", "romaji": "fukou", "english": "Unhappiness", "thai": "ความทุกข์", "arabic": "تعاسة", "russian": "Несчастье"},
    {"kanji": "歓喜", "kana": "かんき", "romaji": "kanki", "english": "Delight", "thai": "ความปีติยินดี", "arabic": "ابتهاج", "russian": "Радость"},
    {"kanji": "苦悩", "kana": "くのう", "romaji": "kunou", "english": "Anguish", "thai": "ความทุกข์ทรมาน", "arabic": "معاناة", "russian": "Мучение"},
    {"kanji": "快感", "kana": "かいかん", "romaji": "kaikan", "english": "Pleasure", "thai": "ความสุข", "arabic": "متعة", "russian": "Удовольствие"},
    {"kanji": "苦痛", "kana": "くつう", "romaji": "kutsuu", "english": "Pain", "thai": "ความเจ็บปวด", "arabic": "ألم", "russian": "Боль"},
    {"kanji": "陶酔", "kana": "とうすい", "romaji": "tousui", "english": "Ecstasy", "thai": "ความมึนเมา", "arabic": "نشوة", "russian": "Экстаз"},
    {"kanji": "苦悶", "kana": "くもん", "romaji": "kumon", "english": "Agony", "thai": "ความทุกข์ทรมาน", "arabic": "عذاب", "russian": "Агония"},
    {"kanji": "恍惚", "kana": "こうこつ", "romaji": "koukotsu", "english": "Rapture", "thai": "ความปลาบปลื้ม", "arabic": "نشوة", "russian": "Восторг"},
    {"kanji": "絶望", "kana": "ぜつぼう", "romaji": "zetsubou", "english": "Despair", "thai": "ความสิ้นหวัง", "arabic": "يأس", "russian": "Отчаяние"},
    {"kanji": "希望", "kana": "きぼう", "romaji": "kibou", "english": "Hope", "thai": "ความหวัง", "arabic": "أمل", "russian": "Надежда"},
    {"kanji": "期待", "kana": "きたい", "romaji": "kitai", "english": "Expectation", "thai": "ความคาดหวัง", "arabic": "توقع", "russian": "Ожидание"},
    {"kanji": "失望", "kana": "しつぼう", "romaji": "shitsubou", "english": "Disappointment", "thai": "ความผิดหวัง", "arabic": "خيبة أمل", "russian": "Разочарование"},
    {"kanji": "楽観", "kana": "らっかん", "romaji": "rakkan", "english": "Optimism", "thai": "การมองโลกในแง่ดี", "arabic": "تفاؤل", "russian": "Оптимизм"},
    {"kanji": "悲観", "kana": "ひかん", "romaji": "hikan", "english": "Pessimism", "thai": "การมองโลกในแง่ร้าย", "arabic": "تشاؤم", "russian": "Пессимизм"},
    {"kanji": "楽天", "kana": "らくてん", "romaji": "rakuten", "english": "Cheerfulness", "thai": "ความร่าเริง", "arabic": "بهجة", "russian": "Жизнерадостность"},
    {"kanji": "憂鬱", "kana": "ゆううつ", "romaji": "yuuutsu", "english": "Depression", "thai": "ความหดหู่", "arabic": "كآبة", "russian": "Депрессия"},
    {"kanji": "熱意", "kana": "ねつい", "romaji": "netsui", "english": "Enthusiasm", "thai": "ความกระตือรือร้น", "arabic": "حماس", "russian": "Энтузиазм"},
    {"kanji": "無気力", "kana": "むきりょく", "romaji": "mukiryoku", "english": "Apathy", "thai": "ความไร้เรี่ยวแรง", "arabic": "لامبالاة", "russian": "Апатия"},
    {"kanji": "意欲", "kana": "いよく", "romaji": "iyoku", "english": "Motivation", "thai": "แรงจูงใจ", "arabic": "حافز", "russian": "Мотивация"},
    {"kanji": "倦怠", "kana": "けんたい", "romaji": "kentai", "english": "Weariness", "thai": "ความเหน็ดเหนื่อย", "arabic": "ملل", "russian": "Усталость"},
    {"kanji": "情熱", "kana": "じょうねつ", "romaji": "jounetsu", "english": "Passion", "thai": "ความหลงใหล", "arabic": "شغف", "russian": "Страсть"},
    {"kanji": "冷淡", "kana": "れいたん", "romaji": "reitan", "english": "Indifference", "thai": "ความเฉยเมย", "arabic": "برود", "russian": "Равнодушие"},
    {"kanji": "愛情", "kana": "あいじょう", "romaji": "aijou", "english": "Affection", "thai": "ความรัก", "arabic": "عاطفة", "russian": "Любовь"},
    {"kanji": "憎悪", "kana": "ぞうお", "romaji": "zouo", "english": "Hatred", "thai": "ความเกลียดชัง", "arabic": "كراهية", "russian": "Ненависть"},
    {"kanji": "好意", "kana": "こうい", "romaji": "koui", "english": "Goodwill", "thai": "ไมตรีจิต", "arabic": "حسن نية", "russian": "Доброжелательность"},
    {"kanji": "敵意", "kana": "てきい", "romaji": "tekii", "english": "Hostility", "thai": "ความเป็นศัตรู", "arabic": "عداء", "russian": "Враждебность"},
    {"kanji": "親愛", "kana": "しんあい", "romaji": "shin'ai", "english": "Affection", "thai": "ความรักใคร่", "arabic": "محبة", "russian": "Нежность"},
    {"kanji": "反感", "kana": "はんかん", "romaji": "hankan", "english": "Antipathy", "thai": "ความรู้สึกไม่ชอบ", "arabic": "نفور", "russian": "Антипатия"},
    {"kanji": "親近感", "kana": "しんきんかん", "romaji": "shinkinkan", "english": "Familiarity", "thai": "ความใกล้ชิด", "arabic": "ألفة", "russian": "Близость"},
    {"kanji": "違和感", "kana": "いわかん", "romaji": "iwakan", "english": "Discomfort", "thai": "ความรู้สึกไม่สบายใจ", "arabic": "انزعاج", "russian": "Дискомфорт"},
    {"kanji": "安堵", "kana": "あんど", "romaji": "ando", "english": "Relief", "thai": "ความโล่งใจ", "arabic": "ارتياح", "russian": "Облегчение"},
    {"kanji": "動転", "kana": "どうてん", "romaji": "douten", "english": "Fluster", "thai": "ความตกใจ", "arabic": "ارتباك", "russian": "Смятение"},
    {"kanji": "恐慌", "kana": "きょうこう", "romaji": "kyoukou", "english": "Panic", "thai": "ความตื่นตระหนก", "arabic": "ذعر", "russian": "Паника"},
    {"kanji": "平然", "kana": "へいぜん", "romaji": "heizen", "english": "Calmness", "thai": "ความสงบ", "arabic": "هدوء", "russian": "Спокойствие"},
    {"kanji": "狼狽", "kana": "ろうばい", "romaji": "roubai", "english": "Confusion", "thai": "ความสับสนวุ่นวาย", "arabic": "حيرة", "russian": "Замешательство"},
    {"kanji": "平穏", "kana": "へいおん", "romaji": "heion", "english": "Tranquility", "thai": "ความสงบสุข", "arabic": "سكينة", "russian": "Покой"},
    {"kanji": "動揺", "kana": "どうよう", "romaji": "douyou", "english": "Disturbance", "thai": "ความไม่สงบ", "arabic": "اضطراب", "russian": "Волнение"},
    {"kanji": "平和", "kana": "へいわ", "romaji": "heiwa", "english": "Peace", "thai": "สันติภาพ", "arabic": "سلام", "russian": "Мир"},
    {"kanji": "激怒", "kana": "げきど", "romaji": "gekido", "english": "Rage", "thai": "ความโกรธจัด", "arabic": "غضب شديد", "russian": "Ярость"},
    {"kanji": "憤慨", "kana": "ふんがい", "romaji": "fungai", "english": "Indignation", "thai": "ความไม่พอใจ", "arabic": "سخط", "russian": "Возмущение"},

    # Attitudes & Behaviors (651-700)
    {"kanji": "態度", "kana": "たいど", "romaji": "taido", "english": "Attitude", "thai": "ทัศนคติ", "arabic": "موقف", "russian": "Отношение"},
    {"kanji": "姿勢", "kana": "しせい", "romaji": "shisei", "english": "Posture", "thai": "ท่าทาง", "arabic": "موقف", "russian": "Поза"},
    {"kanji": "振る舞い", "kana": "ふるまい", "romaji": "furumai", "english": "Behavior", "thai": "พฤติกรรม", "arabic": "سلوك", "russian": "Поведение"},
    {"kanji": "挙動", "kana": "きょどう", "romaji": "kyodou", "english": "Conduct", "thai": "การกระทำ", "arabic": "تصرف", "russian": "Поведение"},
    {"kanji": "品行", "kana": "ひんこう", "romaji": "hinkou", "english": "Character", "thai": "ความประพฤติ", "arabic": "سلوك", "russian": "Нрав"},
    {"kanji": "礼儀", "kana": "れいぎ", "romaji": "reigi", "english": "Etiquette", "thai": "มารยาท", "arabic": "آداب", "russian": "Этикет"},
    {"kanji": "無礼", "kana": "ぶれい", "romaji": "burei", "english": "Rudeness", "thai": "ความหยาบคาย", "arabic": "وقاحة", "russian": "Грубость"},
    {"kanji": "丁寧", "kana": "ていねい", "romaji": "teinei", "english": "Politeness", "thai": "ความสุภาพ", "arabic": "مهذب", "russian": "Вежливость"},
    {"kanji": "粗野", "kana": "そや", "romaji": "soya", "english": "Coarseness", "thai": "ความหยาบกระด้าง", "arabic": "خشونة", "russian": "Грубость"},
    {"kanji": "謙虚", "kana": "けんきょ", "romaji": "kenkyo", "english": "Modesty", "thai": "ความถ่อมตัว", "arabic": "تواضع", "russian": "Скромность"},
    {"kanji": "傲慢", "kana": "ごうまん", "romaji": "gouman", "english": "Arrogance", "thai": "ความหยิ่งยโส", "arabic": "غطرسة", "russian": "Высокомерие"},
    {"kanji": "謙遜", "kana": "けんそん", "romaji": "kenson", "english": "Humility", "thai": "ความอ่อนน้อมถ่อมตัว", "arabic": "تواضع", "russian": "Смирение"},
    {"kanji": "高慢", "kana": "こうまん", "romaji": "kouman", "english": "Haughtiness", "thai": "ความถือตัว", "arabic": "تكبر", "russian": "Надменность"},
    {"kanji": "正直", "kana": "しょうじき", "romaji": "shoujiki", "english": "Honesty", "thai": "ความซื่อสัตย์", "arabic": "صدق", "russian": "Честность"},
    {"kanji": "虚偽", "kana": "きょぎ", "romaji": "kyogi", "english": "Falsehood", "thai": "ความเท็จ", "arabic": "كذب", "russian": "Ложь"},
    {"kanji": "誠実", "kana": "せいじつ", "romaji": "seijitsu", "english": "Sincerity", "thai": "ความจริงใจ", "arabic": "إخلاص", "russian": "Искренность"},
    {"kanji": "偽善", "kana": "ぎぜん", "romaji": "gizen", "english": "Hypocrisy", "thai": "ความหน้าซื่อใจคด", "arabic": "نفاق", "russian": "Лицемерие"},
    {"kanji": "勇敢", "kana": "ゆうかん", "romaji": "yuukan", "english": "Bravery", "thai": "ความกล้าหาญ", "arabic": "شجاعة", "russian": "Храбрость"},
    {"kanji": "臆病", "kana": "おくびょう", "romaji": "okubyou", "english": "Cowardice", "thai": "ความขี้ขลาด", "arabic": "جبن", "russian": "Трусость"},
    {"kanji": "大胆", "kana": "だいたん", "romaji": "daitan", "english": "Boldness", "thai": "ความกล้าหาญ", "arabic": "جرأة", "russian": "Смелость"},
    {"kanji": "小心", "kana": "しょうしん", "romaji": "shoushin", "english": "Timidity", "thai": "ความขี้อาย", "arabic": "خجل", "russian": "Робость"},
    {"kanji": "勤勉", "kana": "きんべん", "romaji": "kinben", "english": "Diligence", "thai": "ความขยัน", "arabic": "اجتهاد", "russian": "Прилежание"},
    {"kanji": "怠惰", "kana": "たいだ", "romaji": "taida", "english": "Laziness", "thai": "ความเกียจคร้าน", "arabic": "كسل", "russian": "Лень"},
    {"kanji": "努力", "kana": "どりょく", "romaji": "doryoku", "english": "Effort", "thai": "ความพยายาม", "arabic": "جهد", "russian": "Усилие"},
    {"kanji": "怠慢", "kana": "たいまん", "romaji": "taiman", "english": "Negligence", "thai": "ความประมาท", "arabic": "إهمال", "russian": "Халатность"},
    {"kanji": "几帳面", "kana": "きちょうめん", "romaji": "kichoumen", "english": "Meticulousness", "thai": "ความพิถีพิถัน", "arabic": "دقة", "russian": "Аккуратность"},
    {"kanji": "ずさん", "kana": "ずさん", "romaji": "zusan", "english": "Sloppiness", "thai": "ความไม่เรียบร้อย", "arabic": "إهمال", "russian": "Небрежность"},
    {"kanji": "寛容", "kana": "かんよう", "romaji": "kanyou", "english": "Tolerance", "thai": "ความอดทน", "arabic": "تسامح", "russian": "Терпимость"},
    {"kanji": "不寛容", "kana": "ふかんよう", "romaji": "fukanyou", "english": "Intolerance", "thai": "ความไม่อดทน", "arabic": "تعصب", "russian": "Нетерпимость"},
    {"kanji": "寛大", "kana": "かんだい", "romaji": "kandai", "english": "Generosity", "thai": "ความใจกว้าง", "arabic": "كرم", "russian": "Великодушие"},
    {"kanji": "狭量", "kana": "きょうりょう", "romaji": "kyouryou", "english": "Narrow-mindedness", "thai": "ความใจแคบ", "arabic": "ضيق أفق", "russian": "Узость взглядов"},
    {"kanji": "楽天的", "kana": "らくてんてき", "romaji": "rakutenteki", "english": "Optimistic", "thai": "มองโลกในแง่ดี", "arabic": "متفائل", "russian": "Оптимистичный"},
    {"kanji": "悲観的", "kana": "ひかんてき", "romaji": "hikanteki", "english": "Pessimistic", "thai": "มองโลกในแง่ร้าย", "arabic": "متشائم", "russian": "Пессимистичный"},
    {"kanji": "積極的", "kana": "せっきょくてき", "romaji": "sekkyokuteki", "english": "Active", "thai": "กระตือรือร้น", "arabic": "نشيط", "russian": "Активный"},
    {"kanji": "消極的", "kana": "しょうきょくてき", "romaji": "shoukyokuteki", "english": "Passive", "thai": "เฉื่อยชา", "arabic": "سلبي", "russian": "Пассивный"},
    {"kanji": "柔軟", "kana": "じゅうなん", "romaji": "juunan", "english": "Flexibility", "thai": "ความยืดหยุ่น", "arabic": "مرونة", "russian": "Гибкость"},
    {"kanji": "頑固", "kana": "がんこ", "romaji": "ganko", "english": "Stubbornness", "thai": "ความดื้อรั้น", "arabic": "عناد", "russian": "Упрямство"},
    {"kanji": "素直", "kana": "すなお", "romaji": "sunao", "english": "Obedience", "thai": "ความเชื่อฟัง", "arabic": "طاعة", "russian": "Покорность"},
    {"kanji": "反抗的", "kana": "はんこうてき", "romaji": "hankouteki", "english": "Rebellious", "thai": "ก้าวร้าว", "arabic": "متمرد", "russian": "Мятежный"},
    {"kanji": "従順", "kana": "じゅうじゅん", "romaji": "juujun", "english": "Obedient", "thai": "เชื่อฟัง", "arabic": "مطيع", "russian": "Послушный"},
    {"kanji": "反抗", "kana": "はんこう", "romaji": "hankou", "english": "Defiance", "thai": "การต่อต้าน", "arabic": "عصيان", "russian": "Неповиновение"},
    {"kanji": "協調", "kana": "きょうちょう", "romaji": "kyouchou", "english": "Coordination", "thai": "ความร่วมมือ", "arabic": "تنسيق", "russian": "Координация"},
    {"kanji": "独断", "kana": "どくだん", "romaji": "dokudan", "english": "Arbitrariness", "thai": "การตัดสินใจเอง", "arabic": "تعسف", "russian": "Самоуправство"},
    {"kanji": "思いやり", "kana": "おもいやり", "romaji": "omoiyari", "english": "Compassion", "thai": "ความเห็นอกเห็นใจ", "arabic": "شفقة", "russian": "Сострадание"},
    {"kanji": "無情", "kana": "むじょう", "romaji": "mujou", "english": "Heartlessness", "thai": "ความไร้ความรู้สึก", "arabic": "قسوة", "russian": "Бессердечие"},
    {"kanji": "親切", "kana": "しんせつ", "romaji": "shinsetsu", "english": "Kindness", "thai": "ความใจดี", "arabic": "لطف", "russian": "Доброта"},
    {"kanji": "冷酷", "kana": "れいこく", "romaji": "reikoku", "english": "Cruelty", "thai": "ความโหดร้าย", "arabic": "قسوة", "russian": "Жестокость"},
    {"kanji": "温厚", "kana": "おんこう", "romaji": "onkou", "english": "Gentleness", "thai": "ความอ่อนโยน", "arabic": "لطف", "russian": "Мягкость"},
    {"kanji": "冷淡", "kana": "れいたん", "romaji": "reitan", "english": "Coldness", "thai": "ความเย็นชา", "arabic": "برود", "russian": "Холодность"},
    {"kanji": "慈悲", "kana": "じひ", "romaji": "jihi", "english": "Mercy", "thai": "ความเมตตา", "arabic": "رحمة", "russian": "Милосердие"},
    {"kanji": "残酷", "kana": "ざんこく", "romaji": "zankoku", "english": "Brutality", "thai": "ความทารุณ", "arabic": "وحشية", "russian": "Жестокость"},

    # Abstract Qualities (701-750)
    {"kanji": "純粋", "kana": "じゅんすい", "romaji": "junsui", "english": "Purity", "thai": "ความบริสุทธิ์", "arabic": "نقاء", "russian": "Чистота"},
    {"kanji": "混濁", "kana": "こんだく", "romaji": "kondaku", "english": "Turbidity", "thai": "ความขุ่น", "arabic": "عكر", "russian": "Мутность"},
    {"kanji": "清潔", "kana": "せいけつ", "romaji": "seiketsu", "english": "Cleanliness", "thai": "ความสะอาด", "arabic": "نظافة", "russian": "Чистота"},
    {"kanji": "汚濁", "kana": "おだく", "romaji": "odaku", "english": "Pollution", "thai": "ความสกปรก", "arabic": "تلوث", "russian": "Загрязнение"},
    {"kanji": "明瞭", "kana": "めいりょう", "romaji": "meiryou", "english": "Clarity", "thai": "ความชัดเจน", "arabic": "وضوح", "russian": "Ясность"},
    {"kanji": "暧昧", "kana": "あいまい", "romaji": "aimai", "english": "Vagueness", "thai": "ความคลุมเครือ", "arabic": "غموض", "russian": "Неясность"},
    {"kanji": "単純", "kana": "たんじゅん", "romaji": "tanjun", "english": "Simplicity", "thai": "ความเรียบง่าย", "arabic": "بساطة", "russian": "Простота"},
    {"kanji": "複雑", "kana": "ふくざつ", "romaji": "fukuzatsu", "english": "Complexity", "thai": "ความซับซ้อน", "arabic": "تعقيد", "russian": "Сложность"},
    {"kanji": "簡潔", "kana": "かんけつ", "romaji": "kanketsu", "english": "Conciseness", "thai": "ความกระชับ", "arabic": "إيجاز", "russian": "Краткость"},
    {"kanji": "冗長", "kana": "じょうちょう", "romaji": "jouchou", "english": "Redundancy", "thai": "ความยืดยาว", "arabic": "إطناب", "russian": "Избыточность"},
    {"kanji": "正確", "kana": "せいかく", "romaji": "seikaku", "english": "Accuracy", "thai": "ความถูกต้อง", "arabic": "دقة", "russian": "Точность"},
    {"kanji": "不正確", "kana": "ふせいかく", "romaji": "fuseikaku", "english": "Inaccuracy", "thai": "ความไม่ถูกต้อง", "arabic": "عدم دقة", "russian": "Неточность"},
    {"kanji": "精密", "kana": "せいみつ", "romaji": "seimitsu", "english": "Precision", "thai": "ความแม่นยำ", "arabic": "دقة", "russian": "Точность"},
    {"kanji": "粗雑", "kana": "そざつ", "romaji": "sozatsu", "english": "Roughness", "thai": "ความหยาบ", "arabic": "خشونة", "russian": "Грубость"},
    {"kanji": "厳密", "kana": "げんみつ", "romaji": "genmitsu", "english": "Strictness", "thai": "ความเข้มงวด", "arabic": "صرامة", "russian": "Строгость"},
    {"kanji": "曖昧", "kana": "あいまい", "romaji": "aimai", "english": "Ambiguity", "thai": "ความคลุมเครือ", "arabic": "غموض", "russian": "Двусмысленность"},
    {"kanji": "鮮明", "kana": "せんめい", "romaji": "senmei", "english": "Vividness", "thai": "ความสดใส", "arabic": "وضوح", "russian": "Яркость"},
    {"kanji": "朦朧", "kana": "もうろう", "romaji": "mourou", "english": "Haziness", "thai": "ความพร่ามัว", "arabic": "ضبابية", "russian": "Смутность"},
    {"kanji": "鋭利", "kana": "えいり", "romaji": "eiri", "english": "Sharpness", "thai": "ความคม", "arabic": "حدة", "russian": "Острота"},
    {"kanji": "鈍重", "kana": "どんじゅう", "romaji": "donjuu", "english": "Dullness", "thai": "ความทึบ", "arabic": "بلادة", "russian": "Тупость"},
    {"kanji": "軽快", "kana": "けいかい", "romaji": "keikai", "english": "Lightness", "thai": "ความเบา", "arabic": "خفة", "russian": "Лёгкость"},
    {"kanji": "重厚", "kana": "じゅうこう", "romaji": "juukou", "english": "Heaviness", "thai": "ความหนัก", "arabic": "ثقل", "russian": "Тяжесть"},
    {"kanji": "敏速", "kana": "びんそく", "romaji": "binsoku", "english": "Quickness", "thai": "ความรวดเร็ว", "arabic": "سرعة", "russian": "Быстрота"},
    {"kanji": "遅鈍", "kana": "ちどん", "romaji": "chidon", "english": "Slowness", "thai": "ความช้า", "arabic": "بطء", "russian": "Медлительность"},
    {"kanji": "迅速", "kana": "じんそく", "romaji": "jinsoku", "english": "Swiftness", "thai": "ความฉับไว", "arabic": "سرعة", "russian": "Быстрота"},
    {"kanji": "緩慢", "kana": "かんまん", "romaji": "kanman", "english": "Slowness", "thai": "ความช้า", "arabic": "بطء", "russian": "Медленность"},
    {"kanji": "整然", "kana": "せいぜん", "romaji": "seizen", "english": "Orderliness", "thai": "ความเป็นระเบียบ", "arabic": "نظام", "russian": "Порядок"},
    {"kanji": "雑然", "kana": "ざつぜん", "romaji": "zatsuzen", "english": "Disorder", "thai": "ความยุ่งเหยิง", "arabic": "فوضى", "russian": "Беспорядок"},
    {"kanji": "整頓", "kana": "せいとん", "romaji": "seiton", "english": "Tidiness", "thai": "ความเรียบร้อย", "arabic": "ترتيب", "russian": "Аккуратность"},
    {"kanji": "混乱", "kana": "こんらん", "romaji": "konran", "english": "Chaos", "thai": "ความสับสน", "arabic": "فوضى", "russian": "Хаос"},
    {"kanji": "統一", "kana": "とういつ", "romaji": "touitsu", "english": "Unity", "thai": "ความเป็นหนึ่งเดียว", "arabic": "وحدة", "russian": "Единство"},
    {"kanji": "分散", "kana": "ぶんさん", "romaji": "bunsan", "english": "Dispersion", "thai": "การกระจาย", "arabic": "تشتت", "russian": "Рассеивание"},
    {"kanji": "集中", "kana": "しゅうちゅう", "romaji": "shuuchuu", "english": "Concentration", "thai": "การรวมศูนย์", "arabic": "تركيز", "russian": "Концентрация"},
    {"kanji": "拡散", "kana": "かくさん", "romaji": "kakusan", "english": "Diffusion", "thai": "การแพร่กระจาย", "arabic": "انتشار", "russian": "Диффузия"},
    {"kanji": "収束", "kana": "しゅうそく", "romaji": "shuusoku", "english": "Convergence", "thai": "การลู่เข้า", "arabic": "تقارب", "russian": "Сходимость"},
    {"kanji": "発散", "kana": "はっさん", "romaji": "hassan", "english": "Divergence", "thai": "การแยกออก", "arabic": "تباعد", "russian": "Расхождение"},
    {"kanji": "凝縮", "kana": "ぎょうしゅく", "romaji": "gyoushuku", "english": "Condensation", "thai": "การควบแน่น", "arabic": "تكثيف", "russian": "Конденсация"},
    {"kanji": "蒸発", "kana": "じょうはつ", "romaji": "jouhatsu", "english": "Evaporation", "thai": "การระเหย", "arabic": "تبخر", "russian": "Испарение"},
    {"kanji": "凝固", "kana": "ぎょうこ", "romaji": "gyouko", "english": "Solidification", "thai": "การแข็งตัว", "arabic": "تجمد", "russian": "Затвердевание"},
    {"kanji": "溶解", "kana": "ようかい", "romaji": "youkai", "english": "Dissolution", "thai": "การละลาย", "arabic": "ذوبان", "russian": "Растворение"},
    {"kanji": "固定", "kana": "こてい", "romaji": "kotei", "english": "Fixation", "thai": "การตรึง", "arabic": "تثبيت", "russian": "Фиксация"},
    {"kanji": "流動", "kana": "りゅうどう", "romaji": "ryuudou", "english": "Fluidity", "thai": "ความลื่นไหล", "arabic": "سيولة", "russian": "Текучесть"},
    {"kanji": "不動", "kana": "ふどう", "romaji": "fudou", "english": "Immobility", "thai": "ความไม่เคลื่อนไหว", "arabic": "ثبات", "russian": "Неподвижность"},
    {"kanji": "変動", "kana": "へんどう", "romaji": "hendou", "english": "Variation", "thai": "ความแปรผัน", "arabic": "تغير", "russian": "Изменчивость"},
    {"kanji": "恒常", "kana": "こうじょう", "romaji": "koujou", "english": "Constancy", "thai": "ความคงที่", "arabic": "ثبات", "russian": "Постоянство"},
    {"kanji": "可変", "kana": "かへん", "romaji": "kahen", "english": "Variability", "thai": "ความแปรผัน", "arabic": "تغير", "russian": "Изменяемость"},
    {"kanji": "不変", "kana": "ふへん", "romaji": "fuhen", "english": "Invariability", "thai": "ความไม่เปลี่ยนแปลง", "arabic": "ثبات", "russian": "Неизменность"},
    {"kanji": "可逆", "kana": "かぎゃく", "romaji": "kagyaku", "english": "Reversibility", "thai": "ความกลับได้", "arabic": "عكسية", "russian": "Обратимость"},
    {"kanji": "不可逆", "kana": "ふかぎゃく", "romaji": "fukagyaku", "english": "Irreversibility", "thai": "ความไม่กลับได้", "arabic": "لا رجعة", "russian": "Необратимость"},
    {"kanji": "可能", "kana": "かのう", "romaji": "kanou", "english": "Possibility", "thai": "ความเป็นไปได้", "arabic": "إمكانية", "russian": "Возможность"},

    # Philosophy & Wisdom (751-800)
    {"kanji": "叡智", "kana": "えいち", "romaji": "eichi", "english": "Wisdom", "thai": "ปัญญา", "arabic": "حكمة", "russian": "Мудрость"},
    {"kanji": "愚昧", "kana": "ぐまい", "romaji": "gumai", "english": "Foolishness", "thai": "ความโง่เขลา", "arabic": "غباء", "russian": "Глупость"},
    {"kanji": "賢明", "kana": "けんめい", "romaji": "kenmei", "english": "Sagacity", "thai": "ความฉลาด", "arabic": "حصافة", "russian": "Благоразумие"},
    {"kanji": "愚鈍", "kana": "ぐどん", "romaji": "gudon", "english": "Stupidity", "thai": "ความโง่", "arabic": "غباء", "russian": "Тупость"},
    {"kanji": "知恵", "kana": "ちえ", "romaji": "chie", "english": "Intelligence", "thai": "สติปัญญา", "arabic": "ذكاء", "russian": "Ум"},
    {"kanji": "無知", "kana": "むち", "romaji": "muchi", "english": "Ignorance", "thai": "ความไม่รู้", "arabic": "جهل", "russian": "Незнание"},
    {"kanji": "啓蒙", "kana": "けいもう", "romaji": "keimou", "english": "Enlightenment", "thai": "การตรัสรู้", "arabic": "تنوير", "russian": "Просвещение"},
    {"kanji": "蒙昧", "kana": "もうまい", "romaji": "moumai", "english": "Obscurantism", "thai": "ความมืดบอด", "arabic": "جهل", "russian": "Мракобесие"},
    {"kanji": "覚悟", "kana": "かくご", "romaji": "kakugo", "english": "Preparedness", "thai": "ความพร้อม", "arabic": "استعداد", "russian": "Готовность"},
    {"kanji": "迷妄", "kana": "めいもう", "romaji": "meimou", "english": "Delusion", "thai": "ความหลงผิด", "arabic": "ضلال", "russian": "Заблуждение"},
    {"kanji": "悟り", "kana": "さとり", "romaji": "satori", "english": "Enlightenment", "thai": "การบรรลุธรรม", "arabic": "استنارة", "russian": "Озарение"},
    {"kanji": "迷い", "kana": "まよい", "romaji": "mayoi", "english": "Bewilderment", "thai": "ความงุนงง", "arabic": "حيرة", "russian": "Смятение"},
    {"kanji": "確信", "kana": "かくしん", "romaji": "kakushin", "english": "Conviction", "thai": "ความเชื่อมั่น", "arabic": "قناعة", "russian": "Убеждённость"},
    {"kanji": "疑念", "kana": "ぎねん", "romaji": "ginen", "english": "Doubt", "thai": "ความสงสัย", "arabic": "شك", "russian": "Сомнение"},
    {"kanji": "信念", "kana": "しんねん", "romaji": "shinnen", "english": "Belief", "thai": "ความเชื่อ", "arabic": "إيمان", "russian": "Убеждение"},
    {"kanji": "猜疑", "kana": "さいぎ", "romaji": "saigi", "english": "Suspicion", "thai": "ความหวาดระแวง", "arabic": "ارتياب", "russian": "Подозрение"},
    {"kanji": "確固", "kana": "かっこ", "romaji": "kakko", "english": "Firmness", "thai": "ความมั่นคง", "arabic": "رسوخ", "russian": "Твёрдость"},
    {"kanji": "動揺", "kana": "どうよう", "romaji": "douyou", "english": "Wavering", "thai": "ความสั่นคลอน", "arabic": "تذبذب", "russian": "Колебание"},
    {"kanji": "堅固", "kana": "けんご", "romaji": "kengo", "english": "Solidity", "thai": "ความแข็งแกร่ง", "arabic": "صلابة", "russian": "Прочность"},
    {"kanji": "脆弱", "kana": "ぜいじゃく", "romaji": "zeijaku", "english": "Fragility", "thai": "ความเปราะบาง", "arabic": "هشاشة", "russian": "Хрупкость"},
    {"kanji": "強固", "kana": "きょうこ", "romaji": "kyouko", "english": "Robustness", "thai": "ความแข็งแรง", "arabic": "متانة", "russian": "Крепость"},
    {"kanji": "虚弱", "kana": "きょじゃく", "romaji": "kyojaku", "english": "Weakness", "thai": "ความอ่อนแอ", "arabic": "ضعف", "russian": "Слабость"},
    {"kanji": "頑強", "kana": "がんきょう", "romaji": "gankyou", "english": "Stubbornness", "thai": "ความดื้อแพ่ง", "arabic": "عناد", "russian": "Упорство"},
    {"kanji": "柔弱", "kana": "じゅうじゃく", "romaji": "juujaku", "english": "Softness", "thai": "ความอ่อนแอ", "arabic": "ضعف", "russian": "Мягкотелость"},
    {"kanji": "剛健", "kana": "ごうけん", "romaji": "gouken", "english": "Vigor", "thai": "ความแข็งแรง", "arabic": "قوة", "russian": "Сила"},
    {"kanji": "柔軟", "kana": "じゅうなん", "romaji": "juunan", "english": "Flexibility", "thai": "ความยืดหยุ่น", "arabic": "مرونة", "russian": "Гибкость"},
    {"kanji": "硬直", "kana": "こうちょく", "romaji": "kouchoku", "english": "Rigidity", "thai": "ความแข็งทื่อ", "arabic": "تصلب", "russian": "Жёсткость"},
    {"kanji": "適応", "kana": "てきおう", "romaji": "tekiou", "english": "Adaptation", "thai": "การปรับตัว", "arabic": "تكيف", "russian": "Адаптация"},
    {"kanji": "順応", "kana": "じゅんのう", "romaji": "junnou", "english": "Acclimation", "thai": "การเคยชิน", "arabic": "تأقلم", "russian": "Привыкание"},
    {"kanji": "不適応", "kana": "ふてきおう", "romaji": "futekiou", "english": "Maladaptation", "thai": "ความไม่เหมาะสม", "arabic": "سوء تكيف", "russian": "Неприспособленность"},
    {"kanji": "調和", "kana": "ちょうわ", "romaji": "chouwa", "english": "Harmony", "thai": "ความสอดคล้อง", "arabic": "انسجام", "russian": "Гармония"},
    {"kanji": "不協和", "kana": "ふきょうわ", "romaji": "fukyouwa", "english": "Disharmony", "thai": "ความไม่กลมกลืน", "arabic": "تنافر", "russian": "Дисгармония"},
    {"kanji": "均衡", "kana": "きんこう", "romaji": "kinkou", "english": "Balance", "thai": "ความสมดุล", "arabic": "توازن", "russian": "Баланс"},
    {"kanji": "不均衡", "kana": "ふきんこう", "romaji": "fukinkou", "english": "Imbalance", "thai": "ความไม่สมดุล", "arabic": "عدم توازن", "russian": "Дисбаланс"},
    {"kanji": "対称", "kana": "たいしょう", "romaji": "taishou", "english": "Symmetry", "thai": "ความสมมาตร", "arabic": "تماثل", "russian": "Симметрия"},
    {"kanji": "非対称", "kana": "ひたいしょう", "romaji": "hitaishou", "english": "Asymmetry", "thai": "ความไม่สมมาตร", "arabic": "عدم تماثل", "russian": "Асимметрия"},
    {"kanji": "釣り合い", "kana": "つりあい", "romaji": "tsuriai", "english": "Equilibrium", "thai": "สมดุล", "arabic": "توازن", "russian": "Равновесие"},
    {"kanji": "偏り", "kana": "かたより", "romaji": "katayori", "english": "Bias", "thai": "ความเอนเอียง", "arabic": "تحيز", "russian": "Перекос"},
    {"kanji": "中立", "kana": "ちゅうりつ", "romaji": "chuuritsu", "english": "Neutrality", "thai": "ความเป็นกลาง", "arabic": "حياد", "russian": "Нейтралитет"},
    {"kanji": "偏向", "kana": "へんこう", "romaji": "henkou", "english": "Inclination", "thai": "ความลำเอียง", "arabic": "ميل", "russian": "Пристрастие"},
    {"kanji": "公正", "kana": "こうせい", "romaji": "kousei", "english": "Fairness", "thai": "ความเป็นธรรม", "arabic": "عدالة", "russian": "Справедливость"},
    {"kanji": "不公正", "kana": "ふこうせい", "romaji": "fukousei", "english": "Unfairness", "thai": "ความไม่เป็นธรรม", "arabic": "ظلم", "russian": "Несправедливость"},
    {"kanji": "公平", "kana": "こうへい", "romaji": "kouhei", "english": "Impartiality", "thai": "ความไม่ลำเอียง", "arabic": "إنصاف", "russian": "Беспристрастность"},
    {"kanji": "不公平", "kana": "ふこうへい", "romaji": "fukouhei", "english": "Partiality", "thai": "ความลำเอียง", "arabic": "محاباة", "russian": "Пристрастность"},
    {"kanji": "客観", "kana": "きゃっかん", "romaji": "kyakkan", "english": "Objectivity", "thai": "ความเป็นกลาง", "arabic": "موضوعية", "russian": "Объективность"},
    {"kanji": "主観", "kana": "しゅかん", "romaji": "shukan", "english": "Subjectivity", "thai": "ความเห็นส่วนตัว", "arabic": "ذاتية", "russian": "Субъективность"},
    {"kanji": "冷静", "kana": "れいせい", "romaji": "reisei", "english": "Calmness", "thai": "ความใจเย็น", "arabic": "هدوء", "russian": "Хладнокровие"},
    {"kanji": "感情的", "kana": "かんじょうてき", "romaji": "kanjouteki", "english": "Emotional", "thai": "เชิงอารมณ์", "arabic": "عاطفي", "russian": "Эмоциональный"},
    {"kanji": "理知的", "kana": "りちてき", "romaji": "richiteki", "english": "Rational", "thai": "เชิงเหตุผล", "arabic": "عقلاني", "russian": "Рациональный"},
    {"kanji": "本能的", "kana": "ほんのうてき", "romaji": "honnouteki", "english": "Instinctive", "thai": "เชิงสัญชาตญาณ", "arabic": "غريزي", "russian": "Инстинктивный"}
]
