# Japanese Vocabulary Database - Part 1 (Words 1-200)
# Advanced Japanese words for language learning

VOCAB_PART1 = [
    # Abstract Concepts & Philosophy (1-30)
    {"kanji": "曖昧", "kana": "あいまい", "romaji": "aimai", "english": "Ambiguous", "thai": "คลุมเครือ", "arabic": "غامض", "russian": "Неясный"},
    {"kanji": "矛盾", "kana": "むじゅん", "romaji": "mujun", "english": "Contradiction", "thai": "ความขัดแย้ง", "arabic": "تناقض", "russian": "Противоречие"},
    {"kanji": "抽象", "kana": "ちゅうしょう", "romaji": "chuushou", "english": "Abstract", "thai": "นามธรรม", "arabic": "مجرد", "russian": "Абстрактный"},
    {"kanji": "具体", "kana": "ぐたい", "romaji": "gutai", "english": "Concrete", "thai": "เป็นรูปธรรม", "arabic": "ملموس", "russian": "Конкретный"},
    {"kanji": "概念", "kana": "がいねん", "romaji": "gainen", "english": "Concept", "thai": "แนวคิด", "arabic": "مفهوم", "russian": "Понятие"},
    {"kanji": "洞察", "kana": "どうさつ", "romaji": "dousatsu", "english": "Insight", "thai": "ความเข้าใจลึกซึ้ง", "arabic": "بصيرة", "russian": "Проницательность"},
    {"kanji": "偏見", "kana": "へんけん", "romaji": "henken", "english": "Prejudice", "thai": "อคติ", "arabic": "تحيز", "russian": "Предубеждение"},
    {"kanji": "葛藤", "kana": "かっとう", "romaji": "kattou", "english": "Conflict", "thai": "ความขัดแย้งภายใน", "arabic": "صراع", "russian": "Конфликт"},
    {"kanji": "懐疑", "kana": "かいぎ", "romaji": "kaigi", "english": "Skepticism", "thai": "ความสงสัย", "arabic": "شك", "russian": "Скептицизм"},
    {"kanji": "憧憬", "kana": "しょうけい", "romaji": "shoukei", "english": "Yearning", "thai": "ความปรารถนา", "arabic": "اشتياق", "russian": "Стремление"},
    {"kanji": "逡巡", "kana": "しゅんじゅん", "romaji": "shunjun", "english": "Hesitation", "thai": "ความลังเล", "arabic": "تردد", "russian": "Колебание"},
    {"kanji": "顕著", "kana": "けんちょ", "romaji": "kencho", "english": "Remarkable", "thai": "โดดเด่น", "arabic": "ملحوظ", "russian": "Заметный"},
    {"kanji": "慎重", "kana": "しんちょう", "romaji": "shinchou", "english": "Cautious", "thai": "ระมัดระวัง", "arabic": "حذر", "russian": "Осторожный"},
    {"kanji": "緻密", "kana": "ちみつ", "romaji": "chimitsu", "english": "Meticulous", "thai": "พิถีพิถัน", "arabic": "دقيق", "russian": "Тщательный"},
    {"kanji": "顕在", "kana": "けんざい", "romaji": "kenzai", "english": "Manifest", "thai": "ชัดเจน", "arabic": "ظاهر", "russian": "Явный"},
    {"kanji": "潜在", "kana": "せんざい", "romaji": "senzai", "english": "Latent", "thai": "แฝง", "arabic": "كامن", "russian": "Скрытый"},
    {"kanji": "恣意", "kana": "しい", "romaji": "shii", "english": "Arbitrary", "thai": "ตามอำเภอใจ", "arabic": "تعسفي", "russian": "Произвольный"},
    {"kanji": "普遍", "kana": "ふへん", "romaji": "fuhen", "english": "Universal", "thai": "สากล", "arabic": "عالمي", "russian": "Универсальный"},
    {"kanji": "妥当", "kana": "だとう", "romaji": "datou", "english": "Reasonable", "thai": "สมเหตุสมผล", "arabic": "معقول", "russian": "Разумный"},
    {"kanji": "洗練", "kana": "せんれん", "romaji": "senren", "english": "Refined", "thai": "ประณีต", "arabic": "مصقول", "russian": "Утончённый"},
    {"kanji": "本質", "kana": "ほんしつ", "romaji": "honshitsu", "english": "Essence", "thai": "แก่นแท้", "arabic": "جوهر", "russian": "Сущность"},
    {"kanji": "原理", "kana": "げんり", "romaji": "genri", "english": "Principle", "thai": "หลักการ", "arabic": "مبدأ", "russian": "Принцип"},
    {"kanji": "理念", "kana": "りねん", "romaji": "rinen", "english": "Ideal", "thai": "อุดมการณ์", "arabic": "مثالي", "russian": "Идеал"},
    {"kanji": "倫理", "kana": "りんり", "romaji": "rinri", "english": "Ethics", "thai": "จริยธรรม", "arabic": "أخلاقيات", "russian": "Этика"},
    {"kanji": "道徳", "kana": "どうとく", "romaji": "doutoku", "english": "Morality", "thai": "ศีลธรรม", "arabic": "أخلاق", "russian": "Мораль"},
    {"kanji": "哲学", "kana": "てつがく", "romaji": "tetsugaku", "english": "Philosophy", "thai": "ปรัชญา", "arabic": "فلسفة", "russian": "Философия"},
    {"kanji": "思想", "kana": "しそう", "romaji": "shisou", "english": "Ideology", "thai": "อุดมการณ์", "arabic": "فكر", "russian": "Идеология"},
    {"kanji": "価値", "kana": "かち", "romaji": "kachi", "english": "Value", "thai": "คุณค่า", "arabic": "قيمة", "russian": "Ценность"},
    {"kanji": "意義", "kana": "いぎ", "romaji": "igi", "english": "Significance", "thai": "ความสำคัญ", "arabic": "أهمية", "russian": "Значение"},
    {"kanji": "真理", "kana": "しんり", "romaji": "shinri", "english": "Truth", "thai": "ความจริง", "arabic": "حقيقة", "russian": "Истина"},

    # Business & Economics (31-60)
    {"kanji": "経済", "kana": "けいざい", "romaji": "keizai", "english": "Economy", "thai": "เศรษฐกิจ", "arabic": "اقتصاد", "russian": "Экономика"},
    {"kanji": "財政", "kana": "ざいせい", "romaji": "zaisei", "english": "Finance", "thai": "การคลัง", "arabic": "مالية", "russian": "Финансы"},
    {"kanji": "投資", "kana": "とうし", "romaji": "toushi", "english": "Investment", "thai": "การลงทุน", "arabic": "استثمار", "russian": "Инвестиция"},
    {"kanji": "利益", "kana": "りえき", "romaji": "rieki", "english": "Profit", "thai": "กำไร", "arabic": "ربح", "russian": "Прибыль"},
    {"kanji": "損失", "kana": "そんしつ", "romaji": "sonshitsu", "english": "Loss", "thai": "ขาดทุน", "arabic": "خسارة", "russian": "Убыток"},
    {"kanji": "競争", "kana": "きょうそう", "romaji": "kyousou", "english": "Competition", "thai": "การแข่งขัน", "arabic": "منافسة", "russian": "Конкуренция"},
    {"kanji": "市場", "kana": "しじょう", "romaji": "shijou", "english": "Market", "thai": "ตลาด", "arabic": "سوق", "russian": "Рынок"},
    {"kanji": "需要", "kana": "じゅよう", "romaji": "juyou", "english": "Demand", "thai": "อุปสงค์", "arabic": "طلب", "russian": "Спрос"},
    {"kanji": "供給", "kana": "きょうきゅう", "romaji": "kyoukyuu", "english": "Supply", "thai": "อุปทาน", "arabic": "عرض", "russian": "Предложение"},
    {"kanji": "貿易", "kana": "ぼうえき", "romaji": "boueki", "english": "Trade", "thai": "การค้า", "arabic": "تجارة", "russian": "Торговля"},
    {"kanji": "企業", "kana": "きぎょう", "romaji": "kigyou", "english": "Enterprise", "thai": "องค์กร", "arabic": "مؤسسة", "russian": "Предприятие"},
    {"kanji": "経営", "kana": "けいえい", "romaji": "keiei", "english": "Management", "thai": "การจัดการ", "arabic": "إدارة", "russian": "Управление"},
    {"kanji": "戦略", "kana": "せんりゃく", "romaji": "senryaku", "english": "Strategy", "thai": "กลยุทธ์", "arabic": "استراتيجية", "russian": "Стратегия"},
    {"kanji": "効率", "kana": "こうりつ", "romaji": "kouritsu", "english": "Efficiency", "thai": "ประสิทธิภาพ", "arabic": "كفاءة", "russian": "Эффективность"},
    {"kanji": "生産", "kana": "せいさん", "romaji": "seisan", "english": "Production", "thai": "การผลิต", "arabic": "إنتاج", "russian": "Производство"},
    {"kanji": "消費", "kana": "しょうひ", "romaji": "shouhi", "english": "Consumption", "thai": "การบริโภค", "arabic": "استهلاك", "russian": "Потребление"},
    {"kanji": "流通", "kana": "りゅうつう", "romaji": "ryuutsuu", "english": "Distribution", "thai": "การจัดจำหน่าย", "arabic": "توزيع", "russian": "Распределение"},
    {"kanji": "契約", "kana": "けいやく", "romaji": "keiyaku", "english": "Contract", "thai": "สัญญา", "arabic": "عقد", "russian": "Контракт"},
    {"kanji": "取引", "kana": "とりひき", "romaji": "torihiki", "english": "Transaction", "thai": "ธุรกรรม", "arabic": "معاملة", "russian": "Сделка"},
    {"kanji": "資本", "kana": "しほん", "romaji": "shihon", "english": "Capital", "thai": "ทุน", "arabic": "رأس مال", "russian": "Капитал"},
    {"kanji": "株式", "kana": "かぶしき", "romaji": "kabushiki", "english": "Stock", "thai": "หุ้น", "arabic": "سهم", "russian": "Акция"},
    {"kanji": "債券", "kana": "さいけん", "romaji": "saiken", "english": "Bond", "thai": "พันธบัตร", "arabic": "سند", "russian": "Облигация"},
    {"kanji": "融資", "kana": "ゆうし", "romaji": "yuushi", "english": "Financing", "thai": "การให้สินเชื่อ", "arabic": "تمويل", "russian": "Финансирование"},
    {"kanji": "破産", "kana": "はさん", "romaji": "hasan", "english": "Bankruptcy", "thai": "ล้มละลาย", "arabic": "إفلاس", "russian": "Банкротство"},
    {"kanji": "合併", "kana": "がっぺい", "romaji": "gappei", "english": "Merger", "thai": "การควบรวม", "arabic": "اندماج", "russian": "Слияние"},
    {"kanji": "買収", "kana": "ばいしゅう", "romaji": "baishuu", "english": "Acquisition", "thai": "การซื้อกิจการ", "arabic": "استحواذ", "russian": "Поглощение"},
    {"kanji": "独占", "kana": "どくせん", "romaji": "dokusen", "english": "Monopoly", "thai": "การผูกขาด", "arabic": "احتكار", "russian": "Монополия"},
    {"kanji": "規制", "kana": "きせい", "romaji": "kisei", "english": "Regulation", "thai": "ข้อบังคับ", "arabic": "تنظيم", "russian": "Регулирование"},
    {"kanji": "税金", "kana": "ぜいきん", "romaji": "zeikin", "english": "Tax", "thai": "ภาษี", "arabic": "ضريبة", "russian": "Налог"},
    {"kanji": "予算", "kana": "よさん", "romaji": "yosan", "english": "Budget", "thai": "งบประมาณ", "arabic": "ميزانية", "russian": "Бюджет"},

    # Academic & Science (61-90)
    {"kanji": "研究", "kana": "けんきゅう", "romaji": "kenkyuu", "english": "Research", "thai": "การวิจัย", "arabic": "بحث", "russian": "Исследование"},
    {"kanji": "実験", "kana": "じっけん", "romaji": "jikken", "english": "Experiment", "thai": "การทดลอง", "arabic": "تجربة", "russian": "Эксперимент"},
    {"kanji": "理論", "kana": "りろん", "romaji": "riron", "english": "Theory", "thai": "ทฤษฎี", "arabic": "نظرية", "russian": "Теория"},
    {"kanji": "仮説", "kana": "かせつ", "romaji": "kasetsu", "english": "Hypothesis", "thai": "สมมติฐาน", "arabic": "فرضية", "russian": "Гипотеза"},
    {"kanji": "検証", "kana": "けんしょう", "romaji": "kenshou", "english": "Verification", "thai": "การตรวจสอบ", "arabic": "تحقق", "russian": "Проверка"},
    {"kanji": "分析", "kana": "ぶんせき", "romaji": "bunseki", "english": "Analysis", "thai": "การวิเคราะห์", "arabic": "تحليل", "russian": "Анализ"},
    {"kanji": "統計", "kana": "とうけい", "romaji": "toukei", "english": "Statistics", "thai": "สถิติ", "arabic": "إحصائيات", "russian": "Статистика"},
    {"kanji": "方程式", "kana": "ほうていしき", "romaji": "houteishiki", "english": "Equation", "thai": "สมการ", "arabic": "معادلة", "russian": "Уравнение"},
    {"kanji": "定理", "kana": "ていり", "romaji": "teiri", "english": "Theorem", "thai": "ทฤษฎีบท", "arabic": "مبرهنة", "russian": "Теорема"},
    {"kanji": "公式", "kana": "こうしき", "romaji": "koushiki", "english": "Formula", "thai": "สูตร", "arabic": "صيغة", "russian": "Формула"},
    {"kanji": "変数", "kana": "へんすう", "romaji": "hensuu", "english": "Variable", "thai": "ตัวแปร", "arabic": "متغير", "russian": "Переменная"},
    {"kanji": "定数", "kana": "ていすう", "romaji": "teisuu", "english": "Constant", "thai": "ค่าคงที่", "arabic": "ثابت", "russian": "Константа"},
    {"kanji": "関数", "kana": "かんすう", "romaji": "kansuu", "english": "Function", "thai": "ฟังก์ชัน", "arabic": "دالة", "russian": "Функция"},
    {"kanji": "微分", "kana": "びぶん", "romaji": "bibun", "english": "Derivative", "thai": "อนุพันธ์", "arabic": "مشتق", "russian": "Производная"},
    {"kanji": "積分", "kana": "せきぶん", "romaji": "sekibun", "english": "Integral", "thai": "ปริพันธ์", "arabic": "تكامل", "russian": "Интеграл"},
    {"kanji": "確率", "kana": "かくりつ", "romaji": "kakuritsu", "english": "Probability", "thai": "ความน่าจะเป็น", "arabic": "احتمال", "russian": "Вероятность"},
    {"kanji": "分子", "kana": "ぶんし", "romaji": "bunshi", "english": "Molecule", "thai": "โมเลกุล", "arabic": "جزيء", "russian": "Молекула"},
    {"kanji": "原子", "kana": "げんし", "romaji": "genshi", "english": "Atom", "thai": "อะตอม", "arabic": "ذرة", "russian": "Атом"},
    {"kanji": "電子", "kana": "でんし", "romaji": "denshi", "english": "Electron", "thai": "อิเล็กตรอน", "arabic": "إلكترون", "russian": "Электрон"},
    {"kanji": "陽子", "kana": "ようし", "romaji": "youshi", "english": "Proton", "thai": "โปรตอน", "arabic": "بروتون", "russian": "Протон"},
    {"kanji": "中性子", "kana": "ちゅうせいし", "romaji": "chuuseishi", "english": "Neutron", "thai": "นิวตรอน", "arabic": "نيوترون", "russian": "Нейтрон"},
    {"kanji": "元素", "kana": "げんそ", "romaji": "genso", "english": "Element", "thai": "ธาตุ", "arabic": "عنصر", "russian": "Элемент"},
    {"kanji": "化合物", "kana": "かごうぶつ", "romaji": "kagoubutsu", "english": "Compound", "thai": "สารประกอบ", "arabic": "مركب", "russian": "Соединение"},
    {"kanji": "反応", "kana": "はんのう", "romaji": "hannou", "english": "Reaction", "thai": "ปฏิกิริยา", "arabic": "تفاعل", "russian": "Реакция"},
    {"kanji": "触媒", "kana": "しょくばい", "romaji": "shokubai", "english": "Catalyst", "thai": "ตัวเร่ง", "arabic": "محفز", "russian": "Катализатор"},
    {"kanji": "溶液", "kana": "ようえき", "romaji": "youeki", "english": "Solution", "thai": "สารละลาย", "arabic": "محلول", "russian": "Раствор"},
    {"kanji": "酸化", "kana": "さんか", "romaji": "sanka", "english": "Oxidation", "thai": "ออกซิเดชัน", "arabic": "أكسدة", "russian": "Окисление"},
    {"kanji": "還元", "kana": "かんげん", "romaji": "kangen", "english": "Reduction", "thai": "รีดักชัน", "arabic": "اختزال", "russian": "Восстановление"},
    {"kanji": "重力", "kana": "じゅうりょく", "romaji": "juuryoku", "english": "Gravity", "thai": "แรงโน้มถ่วง", "arabic": "جاذبية", "russian": "Гравитация"},
    {"kanji": "摩擦", "kana": "まさつ", "romaji": "masatsu", "english": "Friction", "thai": "แรงเสียดทาน", "arabic": "احتكاك", "russian": "Трение"},

    # Psychology & Emotions (91-120)
    {"kanji": "心理", "kana": "しんり", "romaji": "shinri", "english": "Psychology", "thai": "จิตวิทยา", "arabic": "علم نفس", "russian": "Психология"},
    {"kanji": "感情", "kana": "かんじょう", "romaji": "kanjou", "english": "Emotion", "thai": "อารมณ์", "arabic": "عاطفة", "russian": "Эмоция"},
    {"kanji": "精神", "kana": "せいしん", "romaji": "seishin", "english": "Spirit", "thai": "จิตใจ", "arabic": "روح", "russian": "Дух"},
    {"kanji": "意識", "kana": "いしき", "romaji": "ishiki", "english": "Consciousness", "thai": "สติ", "arabic": "وعي", "russian": "Сознание"},
    {"kanji": "無意識", "kana": "むいしき", "romaji": "muishiki", "english": "Unconscious", "thai": "จิตไร้สำนึก", "arabic": "لاوعي", "russian": "Бессознательное"},
    {"kanji": "記憶", "kana": "きおく", "romaji": "kioku", "english": "Memory", "thai": "ความทรงจำ", "arabic": "ذاكرة", "russian": "Память"},
    {"kanji": "認知", "kana": "にんち", "romaji": "ninchi", "english": "Cognition", "thai": "การรับรู้", "arabic": "إدراك", "russian": "Познание"},
    {"kanji": "知覚", "kana": "ちかく", "romaji": "chikaku", "english": "Perception", "thai": "การรับรู้", "arabic": "إحساس", "russian": "Восприятие"},
    {"kanji": "直感", "kana": "ちょっかん", "romaji": "chokkan", "english": "Intuition", "thai": "สัญชาตญาณ", "arabic": "حدس", "russian": "Интуиция"},
    {"kanji": "判断", "kana": "はんだん", "romaji": "handan", "english": "Judgment", "thai": "การตัดสิน", "arabic": "حكم", "russian": "Суждение"},
    {"kanji": "推論", "kana": "すいろん", "romaji": "suiron", "english": "Inference", "thai": "การอนุมาน", "arabic": "استنتاج", "russian": "Умозаключение"},
    {"kanji": "論理", "kana": "ろんり", "romaji": "ronri", "english": "Logic", "thai": "ตรรกะ", "arabic": "منطق", "russian": "Логика"},
    {"kanji": "理性", "kana": "りせい", "romaji": "risei", "english": "Reason", "thai": "เหตุผล", "arabic": "عقل", "russian": "Разум"},
    {"kanji": "欲望", "kana": "よくぼう", "romaji": "yokubou", "english": "Desire", "thai": "ความปรารถนา", "arabic": "رغبة", "russian": "Желание"},
    {"kanji": "衝動", "kana": "しょうどう", "romaji": "shoudou", "english": "Impulse", "thai": "แรงกระตุ้น", "arabic": "دافع", "russian": "Импульс"},
    {"kanji": "抑制", "kana": "よくせい", "romaji": "yokusei", "english": "Suppression", "thai": "การยับยั้ง", "arabic": "كبت", "russian": "Подавление"},
    {"kanji": "不安", "kana": "ふあん", "romaji": "fuan", "english": "Anxiety", "thai": "ความวิตกกังวล", "arabic": "قلق", "russian": "Тревога"},
    {"kanji": "恐怖", "kana": "きょうふ", "romaji": "kyoufu", "english": "Fear", "thai": "ความกลัว", "arabic": "خوف", "russian": "Страх"},
    {"kanji": "喜び", "kana": "よろこび", "romaji": "yorokobi", "english": "Joy", "thai": "ความสุข", "arabic": "فرح", "russian": "Радость"},
    {"kanji": "悲しみ", "kana": "かなしみ", "romaji": "kanashimi", "english": "Sadness", "thai": "ความเศร้า", "arabic": "حزن", "russian": "Грусть"},
    {"kanji": "怒り", "kana": "いかり", "romaji": "ikari", "english": "Anger", "thai": "ความโกรธ", "arabic": "غضب", "russian": "Гнев"},
    {"kanji": "嫉妬", "kana": "しっと", "romaji": "shitto", "english": "Jealousy", "thai": "ความอิจฉา", "arabic": "غيرة", "russian": "Ревность"},
    {"kanji": "羨望", "kana": "せんぼう", "romaji": "senbou", "english": "Envy", "thai": "ความริษยา", "arabic": "حسد", "russian": "Зависть"},
    {"kanji": "共感", "kana": "きょうかん", "romaji": "kyoukan", "english": "Empathy", "thai": "ความเห็นอกเห็นใจ", "arabic": "تعاطف", "russian": "Эмпатия"},
    {"kanji": "同情", "kana": "どうじょう", "romaji": "doujou", "english": "Sympathy", "thai": "ความเห็นใจ", "arabic": "شفقة", "russian": "Сочувствие"},
    {"kanji": "尊敬", "kana": "そんけい", "romaji": "sonkei", "english": "Respect", "thai": "ความเคารพ", "arabic": "احترام", "russian": "Уважение"},
    {"kanji": "軽蔑", "kana": "けいべつ", "romaji": "keibetsu", "english": "Contempt", "thai": "การดูถูก", "arabic": "احتقار", "russian": "Презрение"},
    {"kanji": "誇り", "kana": "ほこり", "romaji": "hokori", "english": "Pride", "thai": "ความภาคภูมิใจ", "arabic": "فخر", "russian": "Гордость"},
    {"kanji": "恥", "kana": "はじ", "romaji": "haji", "english": "Shame", "thai": "ความอับอาย", "arabic": "خجل", "russian": "Стыд"},
    {"kanji": "罪悪感", "kana": "ざいあくかん", "romaji": "zaiakukan", "english": "Guilt", "thai": "ความผิด", "arabic": "شعور بالذنب", "russian": "Вина"},

    # Social & Politics (121-150)
    {"kanji": "政治", "kana": "せいじ", "romaji": "seiji", "english": "Politics", "thai": "การเมือง", "arabic": "سياسة", "russian": "Политика"},
    {"kanji": "民主", "kana": "みんしゅ", "romaji": "minshu", "english": "Democracy", "thai": "ประชาธิปไตย", "arabic": "ديمقراطية", "russian": "Демократия"},
    {"kanji": "独裁", "kana": "どくさい", "romaji": "dokusai", "english": "Dictatorship", "thai": "เผด็จการ", "arabic": "ديكتاتورية", "russian": "Диктатура"},
    {"kanji": "権力", "kana": "けんりょく", "romaji": "kenryoku", "english": "Power", "thai": "อำนาจ", "arabic": "سلطة", "russian": "Власть"},
    {"kanji": "権利", "kana": "けんり", "romaji": "kenri", "english": "Right", "thai": "สิทธิ", "arabic": "حق", "russian": "Право"},
    {"kanji": "義務", "kana": "ぎむ", "romaji": "gimu", "english": "Duty", "thai": "หน้าที่", "arabic": "واجب", "russian": "Обязанность"},
    {"kanji": "自由", "kana": "じゆう", "romaji": "jiyuu", "english": "Freedom", "thai": "เสรีภาพ", "arabic": "حرية", "russian": "Свобода"},
    {"kanji": "平等", "kana": "びょうどう", "romaji": "byoudou", "english": "Equality", "thai": "ความเท่าเทียม", "arabic": "مساواة", "russian": "Равенство"},
    {"kanji": "公平", "kana": "こうへい", "romaji": "kouhei", "english": "Fairness", "thai": "ความยุติธรรม", "arabic": "عدالة", "russian": "Справедливость"},
    {"kanji": "差別", "kana": "さべつ", "romaji": "sabetsu", "english": "Discrimination", "thai": "การเลือกปฏิบัติ", "arabic": "تمييز", "russian": "Дискриминация"},
    {"kanji": "階級", "kana": "かいきゅう", "romaji": "kaikyuu", "english": "Class", "thai": "ชนชั้น", "arabic": "طبقة", "russian": "Класс"},
    {"kanji": "格差", "kana": "かくさ", "romaji": "kakusa", "english": "Disparity", "thai": "ความเหลื่อมล้ำ", "arabic": "تفاوت", "russian": "Неравенство"},
    {"kanji": "貧困", "kana": "ひんこん", "romaji": "hinkon", "english": "Poverty", "thai": "ความยากจน", "arabic": "فقر", "russian": "Бедность"},
    {"kanji": "繁栄", "kana": "はんえい", "romaji": "hanei", "english": "Prosperity", "thai": "ความรุ่งเรือง", "arabic": "ازدهار", "russian": "Процветание"},
    {"kanji": "革命", "kana": "かくめい", "romaji": "kakumei", "english": "Revolution", "thai": "การปฏิวัติ", "arabic": "ثورة", "russian": "Революция"},
    {"kanji": "改革", "kana": "かいかく", "romaji": "kaikaku", "english": "Reform", "thai": "การปฏิรูป", "arabic": "إصلاح", "russian": "Реформа"},
    {"kanji": "保守", "kana": "ほしゅ", "romaji": "hoshu", "english": "Conservative", "thai": "อนุรักษ์นิยม", "arabic": "محافظ", "russian": "Консервативный"},
    {"kanji": "進歩", "kana": "しんぽ", "romaji": "shinpo", "english": "Progress", "thai": "ความก้าวหน้า", "arabic": "تقدم", "russian": "Прогресс"},
    {"kanji": "伝統", "kana": "でんとう", "romaji": "dentou", "english": "Tradition", "thai": "ประเพณี", "arabic": "تقليد", "russian": "Традиция"},
    {"kanji": "文化", "kana": "ぶんか", "romaji": "bunka", "english": "Culture", "thai": "วัฒนธรรม", "arabic": "ثقافة", "russian": "Культура"},
    {"kanji": "習慣", "kana": "しゅうかん", "romaji": "shuukan", "english": "Custom", "thai": "ธรรมเนียม", "arabic": "عادة", "russian": "Обычай"},
    {"kanji": "規範", "kana": "きはん", "romaji": "kihan", "english": "Norm", "thai": "บรรทัดฐาน", "arabic": "معيار", "russian": "Норма"},
    {"kanji": "秩序", "kana": "ちつじょ", "romaji": "chitsujo", "english": "Order", "thai": "ระเบียบ", "arabic": "نظام", "russian": "Порядок"},
    {"kanji": "混沌", "kana": "こんとん", "romaji": "konton", "english": "Chaos", "thai": "ความยุ่งเหยิง", "arabic": "فوضى", "russian": "Хаос"},
    {"kanji": "紛争", "kana": "ふんそう", "romaji": "funsou", "english": "Dispute", "thai": "ข้อพิพาท", "arabic": "نزاع", "russian": "Спор"},
    {"kanji": "戦争", "kana": "せんそう", "romaji": "sensou", "english": "War", "thai": "สงคราม", "arabic": "حرب", "russian": "Война"},
    {"kanji": "平和", "kana": "へいわ", "romaji": "heiwa", "english": "Peace", "thai": "สันติภาพ", "arabic": "سلام", "russian": "Мир"},
    {"kanji": "同盟", "kana": "どうめい", "romaji": "doumei", "english": "Alliance", "thai": "พันธมิตร", "arabic": "تحالف", "russian": "Союз"},
    {"kanji": "条約", "kana": "じょうやく", "romaji": "jouyaku", "english": "Treaty", "thai": "สนธิสัญญา", "arabic": "معاهدة", "russian": "Договор"},
    {"kanji": "外交", "kana": "がいこう", "romaji": "gaikou", "english": "Diplomacy", "thai": "การทูต", "arabic": "دبلوماسية", "russian": "Дипломатия"},

    # Technology & Modern Life (151-180)
    {"kanji": "技術", "kana": "ぎじゅつ", "romaji": "gijutsu", "english": "Technology", "thai": "เทคโนโลยี", "arabic": "تكنولوجيا", "russian": "Технология"},
    {"kanji": "革新", "kana": "かくしん", "romaji": "kakushin", "english": "Innovation", "thai": "นวัตกรรม", "arabic": "ابتكار", "russian": "Инновация"},
    {"kanji": "発明", "kana": "はつめい", "romaji": "hatsumei", "english": "Invention", "thai": "การประดิษฐ์", "arabic": "اختراع", "russian": "Изобретение"},
    {"kanji": "開発", "kana": "かいはつ", "romaji": "kaihatsu", "english": "Development", "thai": "การพัฒนา", "arabic": "تطوير", "russian": "Разработка"},
    {"kanji": "設計", "kana": "せっけい", "romaji": "sekkei", "english": "Design", "thai": "การออกแบบ", "arabic": "تصميم", "russian": "Проектирование"},
    {"kanji": "機械", "kana": "きかい", "romaji": "kikai", "english": "Machine", "thai": "เครื่องจักร", "arabic": "آلة", "russian": "Машина"},
    {"kanji": "装置", "kana": "そうち", "romaji": "souchi", "english": "Device", "thai": "อุปกรณ์", "arabic": "جهاز", "russian": "Устройство"},
    {"kanji": "部品", "kana": "ぶひん", "romaji": "buhin", "english": "Component", "thai": "ชิ้นส่วน", "arabic": "مكون", "russian": "Компонент"},
    {"kanji": "回路", "kana": "かいろ", "romaji": "kairo", "english": "Circuit", "thai": "วงจร", "arabic": "دائرة", "russian": "Схема"},
    {"kanji": "電流", "kana": "でんりゅう", "romaji": "denryuu", "english": "Current", "thai": "กระแสไฟฟ้า", "arabic": "تيار", "russian": "Ток"},
    {"kanji": "電圧", "kana": "でんあつ", "romaji": "denatsu", "english": "Voltage", "thai": "แรงดันไฟฟ้า", "arabic": "جهد", "russian": "Напряжение"},
    {"kanji": "信号", "kana": "しんごう", "romaji": "shingou", "english": "Signal", "thai": "สัญญาณ", "arabic": "إشارة", "russian": "Сигнал"},
    {"kanji": "情報", "kana": "じょうほう", "romaji": "jouhou", "english": "Information", "thai": "ข้อมูล", "arabic": "معلومات", "russian": "Информация"},
    {"kanji": "通信", "kana": "つうしん", "romaji": "tsuushin", "english": "Communication", "thai": "การสื่อสาร", "arabic": "اتصال", "russian": "Связь"},
    {"kanji": "伝達", "kana": "でんたつ", "romaji": "dentatsu", "english": "Transmission", "thai": "การส่ง", "arabic": "نقل", "russian": "Передача"},
    {"kanji": "処理", "kana": "しょり", "romaji": "shori", "english": "Processing", "thai": "การประมวลผล", "arabic": "معالجة", "russian": "Обработка"},
    {"kanji": "記録", "kana": "きろく", "romaji": "kiroku", "english": "Record", "thai": "บันทึก", "arabic": "سجل", "russian": "Запись"},
    {"kanji": "保存", "kana": "ほぞん", "romaji": "hozon", "english": "Storage", "thai": "การจัดเก็บ", "arabic": "تخزين", "russian": "Хранение"},
    {"kanji": "削除", "kana": "さくじょ", "romaji": "sakujo", "english": "Deletion", "thai": "การลบ", "arabic": "حذف", "russian": "Удаление"},
    {"kanji": "復元", "kana": "ふくげん", "romaji": "fukugen", "english": "Restore", "thai": "การกู้คืน", "arabic": "استعادة", "russian": "Восстановление"},
    {"kanji": "暗号", "kana": "あんごう", "romaji": "angou", "english": "Encryption", "thai": "การเข้ารหัส", "arabic": "تشفير", "russian": "Шифрование"},
    {"kanji": "解読", "kana": "かいどく", "romaji": "kaidoku", "english": "Decryption", "thai": "การถอดรหัส", "arabic": "فك تشفير", "russian": "Расшифровка"},
    {"kanji": "接続", "kana": "せつぞく", "romaji": "setsuzoku", "english": "Connection", "thai": "การเชื่อมต่อ", "arabic": "اتصال", "russian": "Подключение"},
    {"kanji": "切断", "kana": "せつだん", "romaji": "setsudan", "english": "Disconnection", "thai": "การตัดการเชื่อมต่อ", "arabic": "قطع", "russian": "Отключение"},
    {"kanji": "起動", "kana": "きどう", "romaji": "kidou", "english": "Boot", "thai": "การบูต", "arabic": "إقلاع", "russian": "Загрузка"},
    {"kanji": "終了", "kana": "しゅうりょう", "romaji": "shuuryou", "english": "Termination", "thai": "การสิ้นสุด", "arabic": "إنهاء", "russian": "Завершение"},
    {"kanji": "更新", "kana": "こうしん", "romaji": "koushin", "english": "Update", "thai": "การอัพเดท", "arabic": "تحديث", "russian": "Обновление"},
    {"kanji": "修正", "kana": "しゅうせい", "romaji": "shuusei", "english": "Correction", "thai": "การแก้ไข", "arabic": "تصحيح", "russian": "Исправление"},
    {"kanji": "障害", "kana": "しょうがい", "romaji": "shougai", "english": "Failure", "thai": "ความล้มเหลว", "arabic": "عطل", "russian": "Сбой"},
    {"kanji": "復旧", "kana": "ふっきゅう", "romaji": "fukkyuu", "english": "Recovery", "thai": "การกู้คืน", "arabic": "استرداد", "russian": "Восстановление"},

    # Nature & Environment (181-200)
    {"kanji": "自然", "kana": "しぜん", "romaji": "shizen", "english": "Nature", "thai": "ธรรมชาติ", "arabic": "طبيعة", "russian": "Природа"},
    {"kanji": "環境", "kana": "かんきょう", "romaji": "kankyou", "english": "Environment", "thai": "สิ่งแวดล้อม", "arabic": "بيئة", "russian": "Окружающая среда"},
    {"kanji": "生態", "kana": "せいたい", "romaji": "seitai", "english": "Ecology", "thai": "นิเวศวิทยา", "arabic": "بيئة", "russian": "Экология"},
    {"kanji": "気候", "kana": "きこう", "romaji": "kikou", "english": "Climate", "thai": "สภาพอากาศ", "arabic": "مناخ", "russian": "Климат"},
    {"kanji": "温暖化", "kana": "おんだんか", "romaji": "ondanka", "english": "Warming", "thai": "ภาวะโลกร้อน", "arabic": "احترار", "russian": "Потепление"},
    {"kanji": "汚染", "kana": "おせん", "romaji": "osen", "english": "Pollution", "thai": "มลพิษ", "arabic": "تلوث", "russian": "Загрязнение"},
    {"kanji": "保護", "kana": "ほご", "romaji": "hogo", "english": "Protection", "thai": "การปกป้อง", "arabic": "حماية", "russian": "Защита"},
    {"kanji": "破壊", "kana": "はかい", "romaji": "hakai", "english": "Destruction", "thai": "การทำลาย", "arabic": "تدمير", "russian": "Разрушение"},
    {"kanji": "再生", "kana": "さいせい", "romaji": "saisei", "english": "Regeneration", "thai": "การฟื้นฟู", "arabic": "تجديد", "russian": "Восстановление"},
    {"kanji": "持続", "kana": "じぞく", "romaji": "jizoku", "english": "Sustainability", "thai": "ความยั่งยืน", "arabic": "استدامة", "russian": "Устойчивость"},
    {"kanji": "資源", "kana": "しげん", "romaji": "shigen", "english": "Resource", "thai": "ทรัพยากร", "arabic": "مورد", "russian": "Ресурс"},
    {"kanji": "枯渇", "kana": "こかつ", "romaji": "kokatsu", "english": "Depletion", "thai": "การหมดสิ้น", "arabic": "استنزاف", "russian": "Истощение"},
    {"kanji": "多様性", "kana": "たようせい", "romaji": "tayousei", "english": "Diversity", "thai": "ความหลากหลาย", "arabic": "تنوع", "russian": "Разнообразие"},
    {"kanji": "絶滅", "kana": "ぜつめつ", "romaji": "zetsumetsu", "english": "Extinction", "thai": "การสูญพันธุ์", "arabic": "انقراض", "russian": "Вымирание"},
    {"kanji": "保全", "kana": "ほぜん", "romaji": "hozen", "english": "Conservation", "thai": "การอนุรักษ์", "arabic": "صيانة", "russian": "Сохранение"},
    {"kanji": "森林", "kana": "しんりん", "romaji": "shinrin", "english": "Forest", "thai": "ป่าไม้", "arabic": "غابة", "russian": "Лес"},
    {"kanji": "海洋", "kana": "かいよう", "romaji": "kaiyou", "english": "Ocean", "thai": "มหาสมุทร", "arabic": "محيط", "russian": "Океан"},
    {"kanji": "大気", "kana": "たいき", "romaji": "taiki", "english": "Atmosphere", "thai": "ชั้นบรรยากาศ", "arabic": "غلاف جوي", "russian": "Атмосфера"},
    {"kanji": "地殻", "kana": "ちかく", "romaji": "chikaku", "english": "Crust", "thai": "เปลือกโลก", "arabic": "قشرة", "russian": "Кора"},
    {"kanji": "火山", "kana": "かざん", "romaji": "kazan", "english": "Volcano", "thai": "ภูเขาไฟ", "arabic": "بركان", "russian": "Вулкан"}
]
